var questions = [
	[ /*physics*//*0*/
		/*0*/"&#9651E =",
		/*1*/"&#9651T =",
		/*2*/"Specific heat capactity is the...",
		/*3*/"&#961; =",
		/*4*/"Mass in a change of state...",
		/*5*/"Specific heat capacity is different for...",
		/*6*/"Ineternal energy is the...",
		/*7*/"Heating either...",
		/*8*/"The energy needed for a change of state is called...",
		/*9*/"Latent heat is the...",
		/*10*/"When a change of state occurs, the temperature...",
		/*11*/"When a change of state occurs, the heat...",
		/*12*/"Specific latent heat is the...",
		/*13*/"E (energy for a change of state) =",
		/*14*/"Latent heat of fusion is the...",
		/*15*/"Latent heat of vaporisation is the...",
		/*16*/"The energy required to change a solid to a liquid is called...",
		/*17*/"The energy required to change a liquid to a solid is called...",
		/*18*/"The energy required to change a liquid to a gas is called...",
		/*19*/"The energy required to change a gas to a liquid is called...",
		/*20*/"The particle model explains...",
		/*21*/"Molecules in gas are in...",
		/*22*/"The temperature is related to the...",
		/*23*/"In a gas at constant volume, the temperature(K) is...",
		/*24*/"In a gas at constant volume, the pressure is...",
		/*25*/"In a gas at constant pressure, the temperature(K) is...",
		/*26*/"In a gas at constant pressure, the volume is...",
		/*27*/"In a gas at constant temperature, the volume is...",
		/*28*/"In a gas at constant temperature, the pressure is...",
		/*29*/"P x V =",
		/*30*/"T/V =",
		/*31*/"T/P =",
		/*32*/"P<sub>1</sub>V<sub>1</sub> =",
		/*33*/"T<sub>1</sub>/V<sub>1</sub> =",
		/*34*/"T<sub>1</sub>/P<sub>1</sub> =",
		/*35*/"Pressure produces a...",
		/*36*/"Doing work on a gas can...",
		/*37*/"When work is done a gas....so the temperature of the gas increases",
		/*38*/"Boyle's law",
		/*39*/"Charles' law",
		/*40*/"The higher the thermal conductivity of a material...",
		/*41*/"The rate of cooling of a building is affected by the...",
		/*42*/"Conduction happens because...",
		/*43*/"Convenction happens because...",
		/*44*/"Heat is transferred by evaporation because...",
		/*45*/"The factors that affect evaporation and condenstion are...",
		/*46*/"All objects (no matter what temperature)...",
		/*47*/"The hotter an object is...",
		/*48*/"Infrared radiation is emitted by...",
		/*49*/"More infrared radiation is emitted by objects that are...",
		/*50*/"The factors that affect the rate at which an object heats are...",
		/*51*/"The bigger the temperature difference between an object and its surroundings...",
		/*52*/"A perfect black body is an object that...",
		/*53*/"A good absorber is a...",
		/*54*/"A good emitter is a...",
		/*55*/"The best possible emitter is a...",
		/*56*/"The intensity and wavelength distribution of any emission depend on the...",
		/*57*/"The temperature of the object controls the",
		/*58*/"An object at constant temperature is absorbing radiation...",
		/*59*/"An object that is heating up is absorbing radiation...",
		/*60*/"The temperature of the Earth depends on the rates of...",
		/*61*/"P =",
		/*62*/"1W =",
		/*63*/"Power is...",
		/*64*/"An example of power using electrical motors is...",
		/*65*/"A system is...",
		/*66*/"When a system changes...",
		/*67*/"When an object is projected upwards, energy changes...",
		/*68*/"When a moving object hits an obstacle, energy changes...",
		/*69*/"When an object is accelerated by a constant force, energy changes...",
		/*70*/"When a vehicle uses its brakes, energy changes...",
		/*71*/"When water is boiled by an electric kettle, energy changes...",
		/*72*/"Efficiency =",
		/*73*/"Nothing can be 100% efficient because...",
		/*74*/"Efficiency is disipated to...",
		/*75*/"Efficiency can be improved by...",
		/*76*/"Efficiency can be written as...",
		/*77*/"The main energy resources available for use on Earth are...",
		/*78*/"A renewable energy resource...",
		/*79*/"The uses of energy resources include...",
		/*80*/"When fossil fuels are burnt...",
		/*81*/"The two types of waves are...||transverse and longitudinal",
		/*82*/"Ripples in water are an example of a...||transverse wave",
		/*83*/"Rarefaction is...||the opposite of compression",
		/*84*/"Diffraction is...||the spreading out of a wave as it travels through a gap",
		/*85*/"Refraction is...||the change in direction a wave as it changes speed",
		/*86*/"Longitudinal waves show areas of...||compression and rarefaction",
		/*87*/"Sound waves are...||longitudinal",
		/*88*/"The difference between transverse and longitudinal waves is that...||transverse waves oscillate perpendicular to the direction of the wave while longitudinal waves oscillate parallel to the direction of the wave.",
		/*89*/"Evidence that when a wave travels through water, the water itself does not move is that...||if something is floating in the water it will only move perpendicular to the wave",
		/*90*/"The amplitude of a wave is the...||maximum displacement",
		/*91*/"The amplitude of a sound wave is the...||volume",
		/*92*/"The amplitude of a wave on...||an amplitude / distance or an amplitude / time graph is the distance between 0 and a peak",
		/*93*/"The wavelength of a wave is the...||length of one full wave",
		/*94*/"The wavelength of a sound wave controls the...||pitch",
		/*95*/"The wavelength of a wave on...||an amplitude / distance graph is the distance between two peaks",
		/*96*/"The frequency of a wave is the...||number of waves per second",
		/*97*/"The frequency of a sound wave is the...||pitch",
		/*98*/"The frequency of a wave on...||an amplitude / time graph is one less than the number of peaks in one second",
		/*99*/"The period of a wave is the...||amount of time over which one wave takes place",
		/*100*/"The period of a sound wave controls the...||pitch",
		/*101*/"The period of a wave on...||an amplitude / time graph is the time between two peaks",
		/*102*/"T (time period) =||1/f",
		/*103*/"Wave speed (v)=||frequency x wavelength",
		/*104*/"The unit for wavelength is...||a vertically flipped y",
		/*105*/"The speed of a sound wave in air can be measured by...||a computer having two microphones at different distances from the sound, the computer starts timing when one microphone hears the sound and stops when the other does (v=d/t) (this can be done without a computer over a distance greater than 50m)",
		/*106*/"The speed of ripples in water can be measured by...||setting up a ripple table where a lamp shows the ripples on the floor, use a motor connected to a wooden rod to create ripples, measure the wavelength with a ruler and count the number of waves in ten seconds (v=fy) or measure the distance one wave travels in ten seconds (v=d/t)",
	],
	[ /*geography*//*1*/
		/*0*/"Weather cells in order from the equator:",
		/*1*/"The weakest weather cell is the...",
		/*2*/"The strongest weather cell is the...",
		/*3*/"Trade winds blow from the...",
		/*4*/"Air at the equator (tropical climate) is...",
		/*5*/"Air at the tropics (sub trpoical climate) is...",
		/*6*/"Air at the UK (temperate climate) is...",
		/*7*/"Air at the poles (polar climate) is...",
		/*8*/"When air rises, pressure is...",
		/*9*/"When air sinks, pressure is...",
		/*10*/"When pressure is high, air is...",
		/*11*/"When pressure is low, air is...",
		/*12*/"Precipitation occurs at...",
		/*13*/"Sun occurs at...",
		/*14*/"Trade winds blow towards the...",
		/*15*/"The most complicated weather cell is the...",
		/*16*/"At high pressure, the temperature is...",
		/*17*/"At low pressure, the temperature is...",
		/*18*/"The temperature is more varied at...",
		/*19*/"The temperature is less varied at...",
		/*20*/"A likely cause for El Ni&#241;o is...",
		/*21*/"El Ni&#241;o take place between...",
		/*22*/"El Ni&#241;o take place in the...",
		/*23*/"In normal conditions in Australia, air is...",
		/*24*/"In normal conditions in South America, air is...",
		/*25*/"The wind between Australia and South America is...",
		/*26*/"Compared to South America, the sea temperature in Australia is...",
		/*27*/"Compared to South America, the sea level in Australia is...",
		/*28*/"Compared to normal conditions, El Ni&#241;o is...",
		/*29*/"Compared to normal conditions, La Ni&#241;a is...",
		/*30*/"During El Ni&#241;o, the trade winds...",
		/*31*/"During El Ni&#241;o, the warmer water ...",
		/*32*/"During El Ni&#241;o, the higher sea level...",
		/*33*/"During El Ni&#241;o, the air pressure...",
		/*34*/"During El Ni&#241;o, the rainfall...",
		/*35*/"During El Ni&#241;o, Australia is under threat of...",
		/*36*/"During El Ni&#241;o, South America is under threat of...",
		/*37*/"During La Ni&#241;a, Australia is under threat of...",
		/*38*/"During La Ni&#241;a, South America is under threat of...",
		/*39*/"During La Ni&#241;a, the trade winds...",
		/*40*/"During La Ni&#241;a, the warmer water ...",
		/*41*/"During La Ni&#241;a, the higher sea level...",
		/*42*/"During La Ni&#241;a, the air pressure...",
		/*43*/"During La Ni&#241;a, the rainfall...",
		/*44*/"Tropical storms originate in...",
		/*45*/"In terms of pressure, tropical storms are a...",
		/*46*/"When a tropical storm forms it is known as a...",
		/*47*/"Tropical storms originate over...",
		/*48*/"Tropical storms are characterised by...",
		/*49*/"When wind speeds are over 119kph, a tropical storms becomes a...",
		/*50*/"Hurricanes occur...",
		/*51*/"An example of a hurricane is...",
		/*52*/"Hurricane Katrina happened in...",
		/*53*/"Hurricane Katrina caused the death of...",
		/*54*/"Hurricane Katrina flooded...",
		/*55*/"Tropical storms form a circular pattern because of the...",
		/*56*/"As air nearer the equator tries to reach the eye of a storm...",
		/*57*/"As air further from the equator tries to reach the eye of a storm...",
		/*58*/"For a tropical storm to form the water must be...",
		/*59*/"Tropcial stroms occur throughout...",
		/*60*/"How many tropical storms occur per year?",
		/*61*/"Are tropical storms getting more frequent?",
		/*62*/"How much more instense have hurricanes storms got in the last 30 years?",
		/*63*/"In terms of tropical storms, El Ni&#241;o causes...",
	],
	[ /*biology*//*2*/
		/*0*/"Plant and animal cells are called...",
		/*1*/"Eukaryotic cells are...",
		/*2*/"Bacterial cells are called...",
		/*3*/"Prokaryotic cells are...",
		/*4*/"Five things that animal cells contain are...",
		/*5*/"Compared to plant and animal cells, bacterial cells are...",
		/*6*/"Three things that bacterial cells contain are...",
		/*7*/"DNA in bacterial cells is in the form of...",
		/*8*/"The function of the nucleus is to...",
		/*9*/"Genetic material in a nucleus is organised as...",
		/*10*/"The function of the cell membrane is to...",
		/*11*/"The function of the mitochondria is to...",
		/*12*/"The function of the chloroplast is to...",
		/*13*/"The function of the plasmids is to...",
		/*14*/"The function of the ribosomes is to...",
		/*15*/"The function of the cytoplasm is to...",
		/*16*/"The function of the vacuole is to...",
		/*17*/"The function of the cell wall is to...",
		/*18*/"Plant cells contain...",
		/*19*/"A sperm cell is specialised by...",
		/*20*/"A red blood cell is specialised by...",
		/*21*/"A nerve cell is specialised by...",
		/*22*/"A muscle cell is specialised by...",
		/*23*/"A root hair cell is specialised by...",
		/*24*/"A xylem cell is specialised by...",
		/*25*/"A phloem cell is specialised by...",
		/*26*/"As an organism develops, cells...",
		/*27*/"Most animal cells differentiate...",
		/*28*/"Most plant cells differentiate...",
		/*29*/"In mature animals, cell division is mainly restricted to...",
		/*30*/"As a cell differentiates, it...",
		/*31*/"Magnification is...",
		/*32*/"Resolution is...",
		/*33*/"A normal microscope is called a...",
		/*34*/"An electron microscope is...",
		/*35*/"Electron microscopes are used to view...",
		/*36*/"When in the correct conditions, bacteria multiply by simple cell division...",
		/*37*/"Bacteria can grow in",
		/*38*/"Bacteria can grow as colonies on...",
		/*39*/"A nutrient broth solution is...",
		/*40*/"To test disinfectants or antibiotics, you need an...",
		/*41*/"Uncontaminated cultures of microorganisms are needed for...",
		/*42*/"To prepare an uncontaminated culture you need to...",
		/*43*/"Can substances diffuse across the cell membrane?",
		/*44*/"Diffusion is the...",
		/*45*/"The concentration gradient is the",
		/*46*/"Factors that effect the rate of diffusion are...",
		/*47*/"Single celled organsims have a...",
		/*48*/"As size increase, surface area to volume ratio...",
		/*49*/"Multicellular organisms need transport systems because...",
		/*50*/"Exchange surfaces are...",
		/*51*/"Exchange surfaces adaptations include...",
		/*52*/"Some of the substances transported in and out of cells by diffusion are...",
		/*53*/"To help with fast exchange, alveoli have...",
		/*54*/"To help with fast exchange, villi (in the small intestine) have...",
		/*55*/"To help with fast exchange, gills have...",
		/*56*/"To help with fast exchange, root hair cells have...",
		/*57*/"To help with fast exchange, leaves have...",
		/*58*/"Osmosis is...",
		/*59*/"Active transport is...",
		/*60*/"The effectiveness of an exchange surface depends on...",
		/*61*/"Active transport is used in plants for...",
		/*62*/"Active transport is used in humans for...",
		/*63*/"Isotonic drinks and energy drinks are used in sport because...",
	],
	[ /*chemistry*//*3*/
		/*0*/"Three limitations of the particle model are...",
		/*1*/"Can physical changes be reversed?",
		/*2*/"Can chemical changes be reversed?",
		/*3*/"Freezing juice is a...",
		/*4*/"Mixing sand and water is a...",
		/*5*/"Dissolving sugar in water is a...",
		/*6*/"Cooking eggs is a...",
		/*7*/"Cooking cakes is a...",
		/*8*/"Steel rusting is a...",
		/*9*/"Acid + Alkali is a...",
		/*10*/"In a physical change...",
		/*11*/"In a chemical change...",
		/*12*/"A meolceule is...",
		/*13*/"Isotopes have...",
		/*14*/"Hydrogen-2 has...",
		/*15*/"Ions have...",
		/*16*/"Atomic radius is the...",
		/*17*/"Bond length is the...",
		/*18*/"In metres, atomic radius is around...",
		/*19*/"In the most suitable unit, atomic radius is around...",
		/*20*/"<sup>z</sup>X is the...",
		/*21*/"<sub>z</sub>X is the...",
		/*22*/"The mass number is the number of...",
		/*23*/"The atomic number is the number of...",
		/*24*/"Most of an atom is...",
		/*25*/"Compared to the atom's size, the nucleus is...",
		/*26*/"Compared to a proton, electrons are...",
		/*27*/"John Dalton made the...",
		/*28*/"Joseph John Thomson made the...",
		/*29*/"Ernest Rutherford made the...",
		/*30*/"Niels Bohr made the...",
		/*31*/"The plum pudding model was made because...",
		/*32*/"The planetary model was made because...",
		/*33*/"The nuclear model was made because...",
		/*34*/"A<sub>r</sub> is...",
		/*35*/"The relative atomic mass is written as...",
		/*36*/"The relative atomic mass is almost the same as...",
		/*37*/"The relative mass unit:",
		/*38*/"The relative formula mass is...",
		/*39*/"The relative formula mass is written as...",
		/*40*/"M<sub>r</sub> is...",
		/*41*/"The empirical formula is...",
		/*42*/"The empirical formula of C<sub>4</sub>H<sub>10</sub> is...",
		/*43*/"In chemistry, pure means...",
		/*44*/"An alloy is...",
		/*45*/"If a substance is impure, its melting point is...",
		/*46*/"If a substance is impure, it melts...",
		/*47*/"The greater the difference in melting point...",
		/*48*/"When a substance dissolves...",
		/*49*/"The solvent is the...",
		/*50*/"The solute is the...",
		/*51*/"The substance that dissolves is called the...",
		/*52*/"The substance that something is dissolved in is called the...",
		/*53*/"Filtration works by...",
		/*54*/"The filtrate is the...",
		/*55*/"The residue is the...",
		/*56*/"The substance that passes through the filter is called the...",
		/*57*/"The substance that does not pass through the filter is called the...",
		/*58*/"In crystallisation, if you heat a solution quickly...",
		/*59*/"In crystallisation, if you heat a solution slowly...",
		/*60*/"Distillation works by...",
		/*61*/"Distillation is used for...",
		/*62*/"Fractional distilation is used for...",
		/*63*/"Fractional distilation works by...",
		/*64*/"In chemistry a phase is...",
		/*65*/"Chromatogrpahy requires...",
		/*66*/"In paper chromatography, the stationary phase is...",
		/*67*/"In paper chromatography, the mobile phase is...",
		/*68*/"In TLC, the stationary phase is...",
		/*69*/"In paper chromatography and TLC, a substance travels further if...",
		/*70*/"R<sub>f</sub> =",
		/*71*/"R<sub>f</sub> values vary from...",
		/*72*/"In gas chromatography, the stationary phase is...",
		/*73*/"In gas chromatography, the mobile phase is...",
		/*74*/"In gas chromatography, the metal column is...",
		/*75*/"In gas chromatography, the sample is injected into the oven...",
		/*76*/"In gas chromatography, the sample is in what state?",
		/*77*/"In gas chromatography, the detector is positioned...",
		/*78*/"In gas chromatography, the detector measures...",
		/*79*/"In gas chromatography, the computer...",
		/*80*/"A chromatogram is...",
		/*81*/"The advantages of TLC over paper chromatography include...",
		/*82*/"TLC stands for...",
		/*83*/"In chromatography, a substance is pure if...",
	],
	[ /*computing*//*4*/
		/*0*/"CPU stands for...",
		/*1*/"ALU stands for...",
		/*2*/"ACC stands for...",
		/*3*/"CU stands for...",
		/*4*/"MAR stands for...",
		/*5*/"MDR stands for...",
		/*6*/"PC stands for...",
		/*7*/"CIR stands for...",
		/*8*/"The seven components in the Von Neumann architecture are...",
		/*9*/"The three buses in the Von Neumann architecture are...",
		/*10*/"The adress bus is used by the...",
		/*11*/"The data bus is used by the...",
		/*12*/"The control bus is used by the...",
		/*13*/"The ALU...",
		/*14*/"The ACC...",
		/*15*/"The CU...",
		/*16*/"The MAR...",
		/*17*/"The MDR...",
		/*18*/"The PC...",
		/*19*/"The CIR...",
		/*20*/"An embedded system provides...",
		/*21*/"An embedded system consists of a...",
		/*22*/"Advantages of an embedded system include...",
		/*23*/"Embedded system example: W...",
		/*24*/"Embedded system example: S...",
		/*25*/"Embedded system example: A...",
		/*26*/"Embedded system example: B...",
		/*27*/"Embedded system example: I...",
		/*28*/"Embedded system example: H...",
		/*29*/"At the start of a fetch-decode-execute cycle...",
		/*30*/"The instruction is split into...",
		/*31*/"The opcode...",
		/*32*/"The operand...",
		/*33*/"The PC is also know as...",
		/*34*/"In the fetch section of a fetch-decode-execute cycle...",
		/*35*/"In the decode section of a fetch-decode-execute cycle...",
		/*36*/"In the execute section of a fetch-decode-execute cycle...",
		/*37*/"The cache...",
		/*38*/"Cache size affects performance...",
		/*39*/"Clock speed...",
		/*40*/"A typical CPU has a clock speed of...",
		/*41*/"Clock speed affects performance...",
		/*42*/"Number of cores affects performance...",
		/*43*/"RISC stands for...",
		/*44*/"CISC stands for...",
		/*45*/"RISC and CISC are types of...",
		/*46*/"One cycle of the CPU refers to...",
		/*47*/"In a RISC processor, each instruction corresponds to...",
		/*48*/"In a CISC processor, each instruction corresponds to...",
		/*49*/"An advantage of CISC is...",
		/*50*/"An advantage of RISC is...",
		/*51*/"Common input devices include...",
		/*52*/"Common output devices include...",
		/*53*/"Common input/output devices include...",
	],
	[ /*music*//*5*/
		/*0*/"In terms of length, fanfares are usually...",
		/*1*/"In terms of volume, fanfares are usually...",
		/*2*/"The lead melody line in a fanfare is usually played by...",
		/*3*/"The rhythm in a fanfare is usally accentuated (brought to attention) by...",
		/*4*/"The tempo in a fanfare is usually kept fast by...",
		/*5*/"Fanfares are usually played in...",
		/*6*/"Rhythmically, fanfares usually use...",
		/*7*/"The texture in a fanfare is usually...",
		/*8*/"Fanfares follow...",
	],
	[ /*spanish*//*6*/
		/*0*/"Vivo en el",
		/*1*/"norte/noreste/noroeste",
		/*2*/"sur/sureste/suroeste",
		/*3*/"este/oeste/centro",
		/*4*/"Inglaterra/Escocia",
		/*5*/"Gales/Irlanda (del norte)",
		/*6*/"En verano/invierno",
		/*7*/"chateo en la red",
		/*8*/"cocino para mi familia",
		/*9*/"descargo canciones",
		/*10*/"escribo correos",
		/*11*/"hago nataci&#243;n/esqu&#237;/windsurf",
		/*12*/"hago una barbacoa",
		/*13*/"juego al baloncesto/f&#250;tbol",
		/*14*/"monto a caballo/en bici",
		/*15*/"nado en el mar",
		/*16*/"salgo con mis amigos/as",
		/*17*/"toco la guitarra",
		/*18*/"trabajo como voluntario/a",
		/*19*/"veo la tele",
		/*20*/"voy al polideportivo/al parque/a un centro comercial",
		/*21*/"voy de paseo",
		/*22*/"siempre",
		/*23*/"a menudo",
		/*24*/"todos los d&#237;as",
		/*25*/"a veces",
		/*26*/"de vez en cuando",
		/*27*/"una vez a la semana",
		/*28*/"dos o tres veces al a&#241;o",
		/*29*/"(casi) nunca",
		/*30*/"Hace buen/mal tiempo",
		/*31*/"Hace calor/fr&#237;o/sol/viento",
		/*32*/"Llueve/Nieva",
		/*33*/"El tiempo es variable",
		/*34*/"El clima es caluroso/soleado",
		/*35*/"Hay niebla/tormenta",
		/*36*/"Hay chubascos",
		/*37*/"Est&#225; nublado",
		/*38*/"Soy adicto/a a...",
		/*39*/"Soy un(a) fan&#225;tico/a de...",
		/*40*/"ya que/dado que/puesto que",
		/*41*/"Prefiero...",
		/*42*/"Me gusta...",
		/*43*/"Me encanta",
		/*44*/"Me mola",
		/*45*/"Me chifla",
		/*46*/"Me flipa",
		/*47*/"Me apasiona...",
		/*48*/"No me gusta (nada)...",
		/*49*/"Odio...",
		/*50*/"A mi padre le gusta...",
		/*51*/"Nos encanta",
		/*52*/"bucear",
		/*53*/"estar al aire libre",
		/*54*/"estar en contacto con los amigos",
		/*55*/"hacer artes marciales",
		/*56*/"hacer deportes acu&#225;ticos",
		/*57*/"ir al cine/a la pista de hielo",
		/*58*/"ir de compras",
		/*59*/"leer (un mont&#243;n de revistas)",
		/*60*/"usar el ordenador",
		/*61*/"ver pel&#237;culas",
		/*62*/"Prefiero veranear...",
		/*63*/"en el extranjero/en Espa&#241;a",
		/*64*/"en la costa/en el campo",
		/*65*/"en la monta&#241;a/en la ciudad",
		/*66*/"hace una semana/un mes/un a&#241;o",
		/*67*/"hace dos semanas/meses/a&#241;os",
		/*68*/"fui de vacaciones a...",
		/*69*/"Francia/Italia/Turqu&#237;a",
		/*70*/"&#191;Con qui&#233;n fuiste?",
		/*71*/"Fui con mi familia/insti",
		/*72*/"Fui con mi mejor amigo/a",
		/*73*/"Fui solo/a",
		/*74*/"&#191;C&#243;mo viajaste?",
		/*75*/"Viaj&#233;...",
		/*76*/"en autocar/avi&#243;n",
		/*77*/"en barco/coche/tren",
		/*78*/"primero",
		/*79*/"luego",
		/*80*/"m&#225;s tarde",
		/*81*/"despu&#233;s",
		/*82*/"finalmente",
		/*83*/"Lo mejor fue cuando...",
		/*84*/"Lo peor fue cuando...",
		/*85*/"aprend&#237; a hacer vela",
		/*86*/"com&#237; muchos helados",
		/*87*/"compr&#233; recuerdos",
		/*88*/"descans&#233;",
		/*89*/"fui al acuario",
		/*90*/"hice turismo",
		/*91*/"llegu&#233; tarde al aeropuerto",
		/*92*/"perd&#237; mi m&#243;vil",
		/*93*/"saqu&#233; fotos",
		/*94*/"tom&#233; el sol",
		/*95*/"tuve un accidente en la playa",
		/*96*/"vi un partido",
		/*97*/"visit&#233; el park",
		/*98*/"vomit&#233; en una monta&#241;a rusa",
		/*99*/"Puedes descubrir el Museo Picasso",
		/*100*/"Puedes disfrutar del Barrio G&#243;tico",
		/*101*/"Puedes pasear por las Ramblas",
		/*102*/"Puedes subir al Monumento a Col&#243;n",
		/*103*/"Puedes ver los barcos en el puerto",
		/*104*/"Me gust&#243;/Me encant&#243;",
		/*105*/"Lo pas&#233; bomba/fenomenal",
		/*106*/"Lo pas&#233; bien/mal/fatal",
		/*107*/"Fue inolvidable/incre&#237;ble",
		/*108*/"Fue impresionante/flipante",
		/*109*/"Fue horroroso",
		/*110*/"Fue un desastre",
		/*111*/"&#191;Qu&#233; tiempo hizo?",
		/*112*/"Hizo buen/mal tiempo",
		/*113*/"Hizo calor/fr&#237;o/sol/viento",
		/*114*/"Hubo niebla/tormenta",
		/*115*/"Llovi&#243;/Nev&#243;",
		/*116*/"Me aloj&#233;",
		/*117*/"Me qued&#233;",
		/*118*/"Nos alojamos",
		/*119*/"Nos quedamos",
		/*120*/"en un albergue juvenil",
		/*121*/"en un apartamento",
		/*122*/"en un camping",
		/*123*/"en un hotel de cinco estrellas",
		/*124*/"en un parador",
		/*125*/"en una casa rural",
		/*126*/"en una pensi&#243;n",
		/*127*/"Fui de crucero",
		/*128*/"Estaba cerca de la playa",
		/*129*/"Estaba en el centro de la ciudad",
		/*130*/"Estaba en las afueras",
		/*131*/"Era...",
		/*132*/"Era acogedor(a)",
		/*133*/"Era antiguo/a",
		/*134*/"Era barato/a",
		/*135*/"Era caro/a",
		/*136*/"Era grande",
		/*137*/"Era lujoso",
		/*138*/"Era moderno/a",
		/*139*/"Era peque&#241;o/a",
		/*140*/"Era ruidoso/a",
		/*141*/"Era tranquilo/a",
		/*142*/"Ten&#237;a/Hab&#237;a...",
		/*143*/"No ten&#237;a ni... ni...",
		/*144*/"No hab&#237;a ni... ni...",
		/*145*/"Tampoco ten&#237;a...",
		/*146*/"aparcamiento",
		/*147*/"bar",
		/*148*/"gimnasio",
		/*149*/"restaurante",
		/*150*/"cafeter&#237;a",
		/*151*/"lavander&#237;a",
		/*152*/"piscina (cubierta)",
		/*153*/"mucho espacio para mi tienda",
		/*154*/"Lo bueno del pueblo/de la ciudad",
		/*155*/"Lo malo era que era...",
		/*156*/"demasiado/muy/bastante...",
		/*157*/"animado/a",
		/*158*/"bonito/a",
		/*159*/"hist&#243;rico/a",
		/*160*/"pintoresco/a",
		/*161*/"tur&#237;stico/a",
		/*162*/"Ten&#237;a mucho ambiente/tr&#225;fico",
		/*163*/"Ten&#237;a mucho que hacer",
		/*164*/"Ten&#237;a mucha contaminaci&#243;n/gente",
		/*165*/"Ten&#237;a muchos espacios verdes",
		/*166*/"Ten&#237;a muchos lugares de inter&#233;s",
		/*167*/"Ten&#237;a muchas discotecas",
		/*168*/"&#191;Hay wifi gratis?",
		/*169*/"&#191;Hay aire acondicionado?",
		/*170*/"en el hotel/las habitaciones",
		/*171*/"&#191;Cu&#225;nto cuesta una habitaci&#243;n (grande)?",
		/*172*/"&#191;A qu&#233; hora se sirve el desayuno?",
		/*173*/"&#191;Cu&#225;ndo est&#225; abierta la piscina?",
		/*174*/"&#191;Cu&#225;nto es el suplemento por...?",
		/*175*/"&#191;Se admiten perros?",
		/*176*/"Quisiera reservar...",
		/*177*/"una habitaci&#243;n individual/doble",
		/*178*/"con/sin balc&#243;n",
		/*179*/"con ba&#241;era/ducha",
		/*180*/"con cama de matrimonio",
		/*181*/"con desayuno incluido",
		/*182*/"con media pensi&#243;n",
		/*183*/"con pensi&#243;n completa",
		/*184*/"con vistas al mar",
		/*185*/"&#191;Para cu&#225;ntas noches?",
		/*186*/"Para catorce noches",
		/*187*/"del diecisiete al treinta y uno de agosto",
		/*188*/"&#191;Puede repetir, por favor?",
		/*189*/"&#191;Puede hablar m&#225;s despacio?",
		/*190*/"Quiero hablar con el director",
		/*191*/"Quiero cambiar de habitaci&#243;n",
		/*192*/"El aire acondicionado",
		/*193*/"El ascensor",
		/*194*/"La ducha",
		/*195*/"La habitaci&#243;n est&#225; sucio/a",
		/*196*/"La luz no funciona",
		/*197*/"Hay ratas en la cama",
		/*198*/"No hay...",
		/*199*/"Necesito...",
		/*200*/"papel higi&#233;nico",
		/*201*/"jab&#243;n/champ&#250;",
		/*202*/"toallas/secador",
		/*203*/"&#161;Socorro!",
		/*204*/"Es inaceptable",
		/*205*/"Lo siento/Perdone",
		/*206*/"El hotel est&#225; completo",
		/*207*/"Por desgracia",
		/*208*/"Por un lado... por otro lado...",
		/*209*/"El primer/&#250;ltimo d&#237;a",
		/*210*/"Al d&#237;a siguiente",
		/*211*/"Tuve/Tuvimos...",
		/*212*/"un accidente/un pinchazo",
		/*213*/"un retraso/una aver&#237;a",
		/*214*/"Tuve/Tuvimos que...",
		/*215*/"esperar mucho tiempo",
		/*216*/"ir al hospital/a la comisar&#237;a",
		/*217*/"llamar a un mec&#225;nico",
		/*218*/"Perd&#237;/Perdimos...",
		/*219*/"el equipaje/la cartera",
		/*220*/"la maleta/las llaves",
		/*221*/"Cuando llegamos...",
		/*222*/"era muy tarde",
		/*223*/"estaba cansado/a",
		/*224*/"la recepci&#243;n ya estaba cerrada",
		/*225*/"acampar",
		/*226*/"decidir",
		/*227*/"alquilar bicicletas",
		/*228*/"coger el telef&#233;rico",
		/*229*/"chocar con",
		/*230*/"hacer alpinismo",
		/*231*/"volver",
		/*232*/"el paisaje",
		/*233*/"la autopista",
		/*234*/"precioso/a",
		/*235*/"el arte dram&#225;tico",
		/*236*/"el dibujo",
		/*237*/"el espa&#241;ol",
		/*238*/"el ingl&#233;s",
		/*239*/"la biolog&#237;a",
		/*240*/"la educaci&#243;n f&#237;sica",
		/*241*/"la f&#237;sica",
		/*242*/"la geograf&#237;a",
		/*243*/"la historia",
		/*244*/"la inform&#225;tica",
		/*245*/"la lengua",
		/*246*/"la qu&#237;mica",
		/*247*/"la religi&#243;n",
		/*248*/"la tecnolog&#237;a",
		/*249*/"los idiomas",
		/*250*/"las empresariales",
		/*251*/"las matem&#225;ticas",
		/*252*/"las ciencias",
		/*253*/"la materia / la asignatura",
		/*254*/"me interesa / me fascina",
		/*255*/"&#191;C&#243;mo es tu insti?",
		/*256*/"Mi d&#237;a preferido es el viernes",
		/*257*/"mi horario",
		/*258*/"&#191;Qu&#233; d&#237;a tienes f&#237;sica?",
		/*259*/"Tengo ingl&#233;s los martes",
		/*260*/"&#191;A qu&#233; hora tienes empresariales",
		/*261*/"a la una / a las dos",
		/*262*/"y / menos cuarto",
		/*263*/"y / menos cinco",
		/*264*/"y media",
		/*265*/"la educaci&#243;n infantil / primaria",
		/*266*/"la educaci&#243;n secundaria",
		/*267*/"el bachillerato",
		/*268*/"la formaci&#243;n profesional",
		/*269*/"La geograf&#237;a es m&#225;s / menos interesante que inform&#225;tica",
		/*270*/"Es mejor / peor que...",
		/*271*/"tan... como...",
		/*272*/"f&#225;cil / dif&#237;cil",
		/*273*/"divertido/a / aburrido/a",
		/*274*/"&#250;til / relevante / pr&#225;ctico/a",
		/*275*/"creativo/a / relajante",
		/*276*/"exacto/a / l&#243;gico/a / exigente",
		/*277*/"Mi profesor(a) de ciencias es...",
		/*278*/"paciente / impaciente",
		/*279*/"tolerante / severo/a",
		/*280*/"listo/a / tonto/a",
		/*281*/"trabajador(a) / perezoso/a",
		/*282*/"simp&#225;tico/a / estricto/a",
		/*283*/"&#191;Qu&#233; tal los estudios?",
		/*284*/"ense&#241;a / explica bien",
		/*285*/"tiene buen sentido del humor",
		/*286*/"tiene expectativas altas",
		/*287*/"crea un buen ambiente de trabajo",
		/*288*/"nunca se enfada",
		/*289*/"me hace pensar",
		/*290*/"nos da consejos / estrategias",
		/*291*/"nos pone muchos deberes",
		/*292*/"el curso acad&#233;mico",
		/*293*/"las pruebas / las evaluaciones",
		/*294*/"suspender / aprobar",
		/*295*/"En mi instituto hay...",
		/*296*/"Mi instituto tiene...",
		/*297*/"un sal&#243;n de actos",
		/*298*/"un comedor",
		/*299*/"un campo de f&#250;tbol",
		/*300*/"un patio",
		/*301*/"&#191;Te interesa qu&#237;mica?",
		/*302*/"&#191;C&#243;mo es tu d&#237;a escolar?",
		/*303*/"una biblioteca",
		/*304*/"una pista de tenis / atletismo",
		/*305*/"unos laboratorios",
		/*306*/"muchas aulas",
		/*307*/"Lo bueno / malo es que...",
		/*308*/"Lo mejor / peor es que...",
		/*309*/"Lo que m&#225;s me gusta es / son...",
		/*310*/"Lo que menos me gusta es / son...",
		/*311*/"no ... ning&#250;n / ninguna",
		/*312*/"nadie",
		/*313*/"mixto / femenino / masculino",
		/*314*/"p&#250;blico / privado",
		/*315*/"moderno / antiguo",
		/*316*/"En mi escuela primaria hab&#237;a...",
		/*317*/"Mi escuela primaria ten&#237;a...",
		/*318*/"ex&#225;menes / deberes / alumnos",
		/*319*/"muebles / espacios verdes",
		/*320*/"tiempo libre",
		/*321*/"oportunidades / instalaciones",
		/*322*/"pizarras interactivas / clases",
		/*323*/"aulas de inform&#225;tica",
		/*324*/"donde jugar",
		/*325*/"poco espacio",
		/*326*/"antes / ahora",
		/*327*/"El edificio / El colegio",
		/*328*/"El d&#237;a escolar",
		/*329*/"(in)adecuado/a / corto/a",
		/*330*/"largo/a",
		/*331*/"Las clases son / eran...",
		/*332*/"Tengo que llevar...",
		/*333*/"Tenemos que llevar...",
		/*334*/"(No) Llevo...",
		/*335*/"(No) Llevamos...",
		/*336*/"Es obligatorio llevar...",
		/*337*/"un jersey (de punto)",
		/*338*/"un vestido",
		/*339*/"una camisa",
		/*340*/"una camiseta",
		/*341*/"una chaqueta (a rayas)",
		/*342*/"una chaqueta de punto",
		/*343*/"una corbata",
		/*344*/"una falda (a cuadros)",
		/*345*/"unos pantalones",
		/*346*/"unos calcetines",
		/*347*/"unos zapatos",
		/*348*/"unos vaqueros",
		/*349*/"unas medias",
		/*350*/"amarillo/a",
		/*351*/"blanco/a",
		/*352*/"negro/a",
		/*353*/"rojo/a",
		/*354*/"morado/a",
		/*355*/"naranja",
		/*356*/"rosa",
		/*357*/"azul",
		/*358*/"verde",
		/*359*/"gris",
		/*360*/"marr&#243;n",
		/*361*/"oscuro / claro",
		/*362*/"a rayas / a cuadros",
		/*363*/"c&#243;modo / inc&#243;modo",
		/*364*/"anticuado / elegante / formal",
		/*365*/"El uniforme",
		/*366*/"mejora la disciplina",
		/*367*/"limita la individualidad",
		/*368*/"da una imagen positiva del insti",
		/*369*/"ahorra tiempo por la ma&#241;ana",
		/*370*/"Est&#225; prohibido...",
		/*371*/"No se permite...",
		/*372*/"No se debe...",
		/*373*/"comer chicle",
		/*374*/"usar el m&#243;vil en clase",
		/*375*/"da&#241;ar las instalaciones",
		/*376*/"ser agresivo o grosero",
		/*377*/"correr en los pasillos",
		/*378*/"llevar piercings",
		/*379*/"Hay que...",
		/*380*/"ser puntual",
		/*381*/"respetar el turno de palabra",
		/*382*/"mantener limpio el patio",
		/*383*/"La norma m&#225;s importante es...",
		/*384*/"respetar a los dem&#225;s",
		/*385*/"Las normas son...",
		/*386*/"necesarias / demasiado severas",
		/*387*/"para fomentar la buena disciplina",
		/*388*/"para limitar la libertad de expresi&#243;n",
		/*389*/"para fastidiar a los alumnos",
		/*390*/"sacar buenas / malas notas",
		/*391*/"Estoy de acuerdo",
		/*392*/"&#161;Qu&#233; va!",
		/*393*/"&#161;Qu&#233; horror!",
		/*394*/"&#161;Qu&#233; bien!",
		/*395*/"Un problema de mi insti es...",
		/*396*/"el estr&#233;s de los ex&#225;menes",
		/*397*/"el acoso escolar",
		/*398*/"la presi&#243;n del grupo",
		/*399*/"Hay (unos) alumnos que...",
		/*400*/"se burlan de otros",
		/*401*/"sufren intimidaci&#243;n",
		/*402*/"tienen miedo de...",
		/*403*/"hacen novillos",
		/*404*/"quieren ser parte de la pandilla",
		/*405*/"son una mala influencia",
		/*406*/"Salgo de casa a las...",
		/*407*/"Las normas del insti",
		/*408*/"voy a pie / andando",
		/*409*/"Voy en bici / en autob&#250;s / en coche",
		/*410*/"Voy en metro / en taxi / en tren",
		/*411*/"Las clases empiezan / terminan...",
		/*412*/"Tenemos siete clases al d&#237;a",
		/*413*/"Cada clase dura cuarenta y cinco minutos",
		/*414*/"El recreo / La hora de comer...",
		/*415*/"llegar / salir / estar",
		/*416*/"violeta",
		/*417*/"llevar ropa de calle",
		/*418*/"ir / comer juntos",
		/*419*/"hacer una visita guiada",
		/*420*/"ver los edificios",
		/*421*/"pasar todo el d&#237;a en...",
		/*422*/"asistir a clases",
		/*423*/"practicar el espa&#241;ol",
		/*424*/"ir de excursi&#243;n",
		/*425*/"tener una programaci&#243;n variada",
		/*426*/"Va a...",
		/*427*/"ser f&#225;cil / guay",
		/*428*/"Las actividades extraescolares",
		/*429*/"Toco la trompeta...",
		/*430*/"Canto en el coro...",
		/*431*/"Voy al club de ajedrez",
		/*432*/"Soy miembro del club de periodismo",
		/*433*/"ajedrez / judo / teatro / periodismo",
		/*434*/"lectores / Ecoescuela / fotograf&#237;a",
		/*435*/"Pienso que / Creo que...",
		/*436*/"muy divertidas",
		/*437*/"algo diferente / un &#233;xito",
		/*438*/"te ayudan a...",
		/*439*/"olvidar las presiones del colegio",
		/*440*/"desarrollar tus talentos",
		/*441*/"hacer nuevos amigos",
		/*442*/"te dan...",
		/*443*/"una sensaci&#243;n de logro",
		/*444*/"m&#225;s confianza",
		/*445*/"la oportunidad de ser creativo/a",
		/*446*/"la oportunidad de expresarte",
		/*447*/"El a&#241;o / trimestre / verano pasado...",
		/*448*/"particip&#233; en un evento especial",
		/*449*/"un concierto / un concurso",
		/*450*/"un torneo",
		/*451*/"gan&#233; un trofeo",
		/*452*/"toqu&#233; un solo",
		/*453*/"conseguimos la clasificaci&#243;n",
		/*454*/"como...",
		/*455*/"tuvimos una charla",
		/*456*/"ganamos una competici&#243;n nacional",
		/*457*/"dimos un concierto",
		/*458*/"&#161;Fue un &#233;xito!",
		/*459*/"Este trimestre / El pr&#243;ximo trimestre...",
		/*460*/"voy a...",
		/*461*/"aprender a...",
		/*462*/"continuar con...",
		/*463*/"&#161;Dejarlo!",
		/*464*/"apuntarme al club de teatro",
		/*465*/"vamos a...",
		/*466*/"montar una obra de teatro",
		/*467*/"conseguir...",
	],
];

var answers = [
	[ /*physics*//*0*/
		/*0*/"mcDT",
		/*1*/"DE/mc",
		/*2*/"energy required to raise 1kg by 1oC",
		/*3*/"m/V",
		/*4*/"is conserved",
		/*5*/"different materials",
		/*6*/"total kinetic and potential energy of all the particles",
		/*7*/"raises the temperature or changes the state",
		/*8*/"latent heat",
		/*9*/"energy needed for a change of state",
		/*10*/"is constant",
		/*11*/"changes",
		/*12*/"energy needed to change the state of 1kg",
		/*13*/"mL",
		/*14*/"energy needed to change the state between solid and liquid",
		/*15*/"energy needed to change the state between liquid and gas",
		/*16*/"latent heat of fusion",
		/*17*/"latent heat of fusion",
		/*18*/"latent heat of vaporisation",
		/*19*/"latent heat of vaporisation",
		/*20*/"states of matter and differences in density",
		/*21*/"constant random motion",
		/*22*/"average kinetic energy",
		/*23*/"directly proportional to the pressure",
		/*24*/"directly proportional to the temperature(K)",
		/*25*/"directly proportional to the volume",
		/*26*/"directly proportional to the temperature(K)",
		/*27*/"inversely proportional to the pressure",
		/*28*/"inversely proportional to the volume",
		/*29*/"k",
		/*30*/"k",
		/*31*/"k",
		/*32*/"P2V2",
		/*33*/"T2/V2",
		/*34*/"T2/P2",
		/*35*/"net force at right angles to the walls of the container",
		/*36*/"increase its temperature",
		/*37*/"kinetic energy is transferred to the particles so the average kinetic energy increases",
		/*38*/"The pressure of a gas at constant temperature is inversely proportional to its volume",
		/*39*/"The volume of a gas at constant pressure is directly proportional to its temperature(K)",
		/*40*/"the higher the rate of transfer by conduction across the material",
		/*41*/"thickness and thermal conductivity of its walls",
		/*42*/"when particles collide the slower energy is transferred (usually) from the faster one to the slower one",
		/*43*/"the hotter particles move faster and volume is proprtional to temperature so they take up more space with the same mass so the density is lower so the hotter particles rise",
		/*44*/"the hotter particles have enough energy to leave the object as a gas (evaporation) leaving the cooler particles behind",
		/*45*/"temperature, surface area, wind, humidity",
		/*46*/"emmit and absorb infrared radiation",
		/*47*/"the more infrared radiation it emitts",
		/*48*/"all objects",
		/*49*/"hotter",
		/*50*/"the surface area, volume and material of the object and the nature of the surface it is touching",
		/*51*/"the faster heat is transferred",
		/*52*/"absorbs all radiation",
		/*53*/"good emitter",
		/*54*/"good absorber",
		/*55*/"perfect black body",
		/*56*/"temperature of the object",
		/*57*/"intensity and wavelength distribution of its emission",
		/*58*/"at the same rate than it is emitting radiation",
		/*59*/"at a faster rate than it is emitting radiation",
		/*60*/"absorption, emission and reflection",
		/*61*/"&#9651E/t or W/t",
		/*62*/"1J/s",
		/*63*/"the rate at which energy is transferred or the rate at which work is done",
		/*64*/"if they both lift the same weight the same distance but one does it faster then the energy transferred was the same but the power was higher in the faster one",
		/*65*/"an object or group of objects",
		/*66*/"there are changes in the way energy is stored",
		/*67*/"from kinetic to potential",
		/*68*/"from kinetic in the moving object to kinetic in the obstacle",
		/*69*/"from the source of the force to kinetic in the object",
		/*70*/"from kinetic to heat",
		/*71*/"from electric to heat",
		/*72*/"useful energy output / total energy input × 100",
		/*73*/"there will always be resistance",
		/*74*/"heat and often sound because of the resistance",
		/*75*/"lubrication to reduce resistance and thermal insulation to reduce heat loss to the surroundings.",
		/*76*/"a percentage or a decimal",
		/*77*/"fossil fuels(coal, crude oil, natural gas), nuclear fuel, biofuel, wind, hydro electricity, geothermal, tides, the Sun, water waves",
		/*78*/"can be replenished as it used",
		/*79*/"heating, transport and energy generation",
		/*80*/"they release harmful greenhouse gasses that heat heat up the planet",
	],
	[ /*geography*//*1*/
		/*0*/"Hadley, Ferrel, Polar",
		/*1*/"Polar cell",
		/*2*/"Hadley cell",
		/*3*/"East",
		/*4*/"rising",
		/*5*/"sinking",
		/*6*/"rising",
		/*7*/"sinking",
		/*8*/"low",
		/*9*/"high",
		/*10*/"sinking",
		/*11*/"rising",
		/*12*/"low pressure",
		/*13*/"high pressure",
		/*14*/"equator",
		/*15*/"Ferrel cell",
		/*16*/"varied",
		/*17*/"constant",
		/*18*/"high pressure",
		/*19*/"low pressure",
		/*20*/"small changes in sea surface temperatures caused by strong storms in the western region of the Pacific",
		/*21*/"Australia and South America",
		/*22*/"South Pacific",
		/*23*/"rising",
		/*24*/"sinking",
		/*25*/"the trade wind",
		/*26*/"warmer",
		/*27*/"higher",
		/*28*/"less extreme or the opposite",
		/*29*/"more extreme",
		/*30*/"weaken, stop or reverse",
		/*31*/"spreads away from Australia towards South America",
		/*32*/"spreads away from Australia towards South America",
		/*33*/"becomes low in Australia and high in South America",
		/*34*/"stops in Australia and starts in America",
		/*35*/"droughts",
		/*36*/"floods",
		/*37*/"floods",
		/*38*/"droughts",
		/*39*/"gets stronger",
		/*40*/"gets warmer",
		/*41*/"gets higher",
		/*42*/"gets more extreme",
		/*43*/"gets more extreme",
		/*44*/"the tropics",
		/*45*/"low pressure system",
		/*46*/"tropical depression",
		/*47*/"warm water",
		/*48*/"high winds and heavy rain",
		/*49*/"hurricane, typhoon or cyclone",
		/*50*/"in the north atlantic and east pacific",
		/*51*/"Hurricane Katrina",
		/*52*/"2005",
		/*53*/"1836 people",
		/*54*/"80% of New Orleans",
		/*55*/"corriolis effect",
		/*56*/"it is travelling faster than the eye to it ends up too far forward",
		/*57*/"it is travelling slower than the eye so it ends up too far backward",
		/*58*/"at least 26.5oC and at least 50m deep",
		/*59*/"Summer and Autumn",
		/*60*/"aproximately 80",
		/*61*/"no",
		/*62*/"70%",
		/*63*/"more in the South East Pacif and less in the Atlantic",
	],
	[ /*biology*//*2*/
		/*0*/"Eukaryotic cells",
		/*1*/"plant and animal cells",
		/*2*/"Prokaryotic cells",
		/*3*/"bacterial cells",
		/*4*/"a nucleus, cytoplasm, a cell membrane, mitochondria, ribosomes",
		/*5*/"much smaller",
		/*6*/"cytoplasm, cell membrane, cell wall",
		/*7*/"a single DNA loop with more small rings called plasmids",
		/*8*/"contain the DNA to control  the activities of the cell",
		/*9*/"DNA molecules that form chromosomes",
		/*10*/"control what enters/exits the cell",
		/*11*/"be a site for respiration",
		/*12*/"abosorb light to make food by photosynthesis",
		/*13*/"provide genetic advantages such as antibiotic resistance",
		/*14*/"be a site for protein synthesis",
		/*15*/"be a site for most chemical reactions",
		/*16*/"fill with sap and keep the cell enlarged",
		/*17*/"strengthen the cell",
		/*18*/"the same as animal cells, chloroplast, a vacuole, a cell wall",
		/*19*/"having a tail to help it move and lots of mitochondria for energy",
		/*20*/"being small, having lots of haemoglobing to carry oxygen, not having a nucleus or mitochondria and little cytoplasm to carry lots of oxygen",
		/*21*/"having long fibres to carry impulses to/from the brain, has long dendrites to make connections with other neurons",
		/*22*/"having lots of mitochondria and glycogen for energy",
		/*23*/"having increased surface area for water uptake, large vauole to maintain water potential, lots of mitochondria for energy for active transport",
		/*24*/"having lots of lignin in the cell wall to withstand the pressure, the cells are dead",
		/*25*/"having very few organelles but are kept alive by neighbouring cells",
		/*26*/"differentiate to form different types of cells",
		/*27*/"at an early stage",
		/*28*/"at any point in their life",
		/*29*/"repair and replacement",
		/*30*/"aquires different sub cellular structures making it specialised",
		/*31*/"How many times bigger an object appears compared to its actual size",
		/*32*/"The smallest distance between two points that can be seen as seperate entities",
		/*33*/"light microscope",
		/*34*/"much stronger than a light microscope",
		/*35*/"sub cellular structures",
		/*36*/"once every 20 minutes",
		/*37*/"a nutrient broth solution",
		/*38*/"an agar gel plate",
		/*39*/"a liquid version of an agar gel plate",
		/*40*/"uncontaminated culture of microorganisms",
		/*41*/"testing disinfectants and antibiotics",
		/*42*/"steralise petri dishes and culture media, steralise the inoculating loop using a flame, secure the lid of the petri dish with tape to prevent air contamination, store upside down to prevent anything falling on the agar surface",
		/*43*/"yes",
		/*44*/"movement of particles from an area of high concentration to an area of low concentration",
		/*45*/"difference in concentration",
		/*46*/"concentration gradient, temperature, area of contact",
		/*47*/"relatively high surface area to volume ratio allowing enough transport in and out the cell to meet the needs of the organism",
		/*48*/"decreases",
		/*49*/"their size is big so their SA/V ratio is too small so they use smaller cells to transport what they need",
		/*50*/"surfaces wherer diffusion takes place",
		/*51*/"thin barriers and large surface area",
		/*52*/"oxygen, carbon dioxide and urea",
		/*53*/"a high surface area, one cell think walls and moist walls so oxygen can dissolve into it and diffuse faster",
		/*54*/"a high surface area with microvilli making the surface area even higher and one cell think walls",
		/*55*/"a high surface area, one cell think walls and the blood flows in the opposite direction to the water",
		/*56*/"a high surface area, can penetrate between soil particles to reduce the distance and they contain a lot of mitochondria for active transport",
		/*57*/"a high surface area and very thin walls",
		/*58*/"the process of diffusion through a semi permeable membrane against the concentration gradient",
		/*59*/"the movement of molecules across a membrane assisted by enzymes and requiring energy",
		/*60*/"having a large surface area, a membrane that is thin, an efficient blood supply and being ventilated",
		/*61*/"transporting mineral into the roots",
		/*62*/"glucose to enter the blood from the small intestine",
		/*63*/"they contain a lot of sugar so the body can anaerobically respire",
	],
	[ /*chemistry*//*3*/
		/*0*/"forces between particles, size of particles, space between particles",
		/*1*/"yes",
		/*2*/"no",
		/*3*/"physical change",
		/*4*/"physical change",
		/*5*/"physical change",
		/*6*/"chemical change",
		/*7*/"chemical change",
		/*8*/"chemical change",
		/*9*/"chemical change",
		/*10*/"no new substances are produced",
		/*11*/"new substances are produced",
		/*12*/"two or more atoms joined together",
		/*13*/"different numbers of neutrons",
		/*14*/"two neutrons",
		/*15*/"different numbers of electrons",
		/*16*/"distance between the centre and the edge of an atom",
		/*17*/"distance between the centres of two connected atoms",
		/*18*/"10-10",
		/*19*/"0.1nm",
		/*20*/"mass number",
		/*21*/"atomic number",
		/*22*/"protons and neutrons",
		/*23*/"protons",
		/*24*/"empty space",
		/*25*/"100,000 times smaller",
		/*26*/"2000 times smaller",
		/*27*/"solid state model of the atom",
		/*28*/"plum pudding model of the atom",
		/*29*/"planetary model of the atom",
		/*30*/"nuclear model of the atom",
		/*31*/"cathode rays (beams of electrons) changed direction and electric and magnetic fields",
		/*32*/"alpha particles (helium nuclei) occasionally bounced off gold leaf",
		/*33*/"electrons would spiral inwards in the planetary model",
		/*34*/"the relative atomic mass",
		/*35*/"Ar",
		/*36*/"the mass number",
		/*37*/"none",
		/*38*/"the total of the relative atomic masses in a substance",
		/*39*/"Mr",
		/*40*/"the relative formula mass",
		/*41*/"a simplified version of a chemical formula",
		/*42*/"C2H5",
		/*43*/"only contains one element",
		/*44*/"a mixture of a metal and one other element",
		/*45*/"lower",
		/*46*/"over a range of temperatures",
		/*47*/"the more impure a substance is",
		/*48*/"its particles become mixed with solvent but not bonded",
		/*49*/"substance that dissolves",
		/*50*/"substance that something is dissolved in",
		/*51*/"solute",
		/*52*/"solvent",
		/*53*/"having holes small enough for liquids to get through but not solids",
		/*54*/"substance that passes through the filter",
		/*55*/"substance that does not pass through the filter",
		/*56*/"filtrate",
		/*57*/"residue",
		/*58*/"you get a powder",
		/*59*/"you get a crystal",
		/*60*/"heating both substances until one of them evaporates and is cooled in the condenser",
		/*61*/"separating two substances",
		/*62*/"separating two or more substances",
		/*63*/"heating all the substances until they evaporate, each one will condense at a different point on the fractionating column or will get past the whole column",
		/*64*/"any substance in solid, liquid or gas state",
		/*65*/"a stationary phase and a mobile phase",
		/*66*/"absorbant paper",
		/*67*/"a solvent in the liquid state",
		/*68*/"a thin layer of obsorbent material (typically silica gel) on a sheet of glass, platic or aluminium",
		/*69*/"it forms stronger bonds with the mobile phase than the stationary phase",
		/*70*/"distance travelled by substance / distance travelled by solvent",
		/*71*/"0 to 1",
		/*72*/"silica or alumuna powder packed into a metal column",
		/*73*/"an unreactive carrier gas such as nitrogen which does not react with the sample",
		/*74*/"coiled so it can fit in a very hot oven",
		/*75*/"at a different place to the carrier gas but joins it before it reaches the stationary phase",
		/*76*/"gas",
		/*77*/"after the oven",
		/*78*/"how long each substance takes to leave the oven",
		/*79*/"turns the results from the detector into a chromatogram",
		/*80*/"the result of paper chromatography and TLC",
		/*81*/"it is quicker, more sensitive so less sample is needed, there is a larger range of stationary phases and solvents to choose from",
		/*82*/"thin layer chromatography",
		/*83*/"it only has one dot",
	],
	[ /*computing*//*4*/
		/*0*/"Central Processing Unit",
		/*1*/"Arithmetic and Logic Unit",
		/*2*/"Accumulator",
		/*3*/"Control Unit",
		/*4*/"Memory Address Register",
		/*5*/"Memory Data Register",
		/*6*/"Program Counter",
		/*7*/"Current Instruction Register",
		/*8*/"ALU, ACC, CU, MAR, MDR, PC, CIR",
		/*9*/"Address bus, Data bus, Control bus",
		/*10*/"MAR",
		/*11*/"MDR",
		/*12*/"CU",
		/*13*/"does all the maths",
		/*14*/"stores the data being used in ALU",
		/*15*/"controls what the other components in the CPU are doing",
		/*16*/"stores the memory address to be fetched or sent to",
		/*17*/"stores data that has been fetched from or to be sent to the memory",
		/*18*/"stores the memory address of the next instruction",
		/*19*/"stores the memory address of the current instruction",
		/*20*/"one or two specific functions",
		/*21*/"microprocessor that takes in an input, processes it, and povides an output",
		/*22*/"Smaller and cheaper because there is less wastage",
		/*23*/"Washing machine",
		/*24*/"Smoke detector",
		/*25*/"Air conditioning",
		/*26*/"Blood pressure monitor",
		/*27*/"Insulin pump",
		/*28*/"Headlight position control",
		/*29*/"the data and the instruction are loaded into the memory by the operating system",
		/*30*/"the opcode and the operand",
		/*31*/"tells the CPU what to do",
		/*32*/"tells the CPU where to do the opcode",
		/*33*/"instruction pointer (IP) or instruction address register (IAR)",
		/*34*/"the PC passes the memory address of the instruction to the MAR, the MAR sends the address to the memory using the address bus and the memory sends the data at that address to the MDR using the data bus",
		/*35*/"the CPU uses an instruction set (set of commands written in machine language) to decode an instruction",
		/*36*/"the control unit will tell the component needed to carry out the instruction (ALU for maths or MDR for sending it back to the memory)",
		/*37*/"stores commonly used instructions and data so they can be accessed quickly",
		/*38*/"because if it is bigger then more instructions and data can be accessed quickly",
		/*39*/"is the number of fetch-decode-execute cycles carried out per second (1 cycle per second = 1Hz)",
		/*40*/"2GHz (2 million cycles per second)",
		/*41*/"because if it is faster it will carry out more instruction per second",
		/*42*/"because if there are twice as many cores there are twice as many instructions carried out per second but is not always supported",
		/*43*/"Reduced Instruction Set Computer",
		/*44*/"Complex Instruction Set Computer",
		/*45*/"processor",
		/*46*/"one fetch-decode-execute cycle",
		/*47*/"a single operation that runs in one fetch-decode-execute cycle",
		/*48*/"a single operation that may run in multiple fetch-decode-execute cycles",
		/*49*/"your programs will be shorter",
		/*50*/"simple hardware is used meaning a lower power usage",
		/*51*/"keyboard, mouse, touchscreen, buttons, controllers, microphone, camera",
		/*52*/"monitor, speaker, printer",
		/*53*/"HDD, USB, CD, DVD (storage)",
	],
	[ /*music*//*5*/
		/*0*/"short",
		/*1*/"loud",
		/*2*/"the brass, particularly trumpets",
		/*3*/"trombone, tuba, french horn",
		/*4*/"drums and percussion",
		/*5*/"major scales",
		/*6*/"repeated rhythms (semi quavors, dotted rhythms, triplets) and repeated notes at the same pitch",
		/*7*/"contrapuntal",
		/*8*/"chords",
	],
	[ /*spanish*//*6*/
		/*0*/"I live in the",
		/*1*/"north/north east/north west",
		/*2*/"south/south east/south west",
		/*3*/"east/west/centre",
		/*4*/"England/Scotland",
		/*5*/"Wales/(Northern) Ireland",
		/*6*/"in summer/winter",
		/*7*/"chat online",
		/*8*/"cook for my family",
		/*9*/"download songs",
		/*10*/"write emails",
		/*11*/"I go swimming/skiing/windsurfing",
		/*12*/"I have a barbecue",
		/*13*/"I play basketball/football",
		/*14*/"horseriding/cycling",
		/*15*/"I swim in the sea",
		/*16*/"I go out with my friends",
		/*17*/"I play guitar",
		/*18*/"I work as a volunteer",
		/*19*/"I watch TV",
		/*20*/"I go to the sports centre/the park/the shopping centre",
		/*21*/"I go for a walk",
		/*22*/"always",
		/*23*/"often",
		/*24*/"every day",
		/*25*/"sometimes",
		/*26*/"from time to time",
		/*27*/"once a week",
		/*28*/"two or three times a year",
		/*29*/"(almost) never",
		/*30*/"it is good/bad weather",
		/*31*/"it is hot/cold/sunny/windy",
		/*32*/"it is raining/snowing",
		/*33*/"the weather is variable",
		/*34*/"the weather is hot/sunny",
		/*35*/"it is foggy/stormy",
		/*36*/"there are showers",
		/*37*/"it is cloudy",
		/*38*/"I am addicted to",
		/*39*/"I am a fan of",
		/*40*/"given that/since",
		/*41*/"I prefer",
		/*42*/"I like",
		/*43*/"I love",
		/*44*/"I love",
		/*45*/"I love",
		/*46*/"I love",
		/*47*/"I love",
		/*48*/"I do not like (at all)",
		/*49*/"I hate",
		/*50*/"My dad likes",
		/*51*/"We love",
		/*52*/"diving",
		/*53*/"being outside",
		/*54*/"staying in contact with my friends",
		/*55*/"doing martial arts",
		/*56*/"doing water sports",
		/*57*/"going to the cinema/ice rink",
		/*58*/"going shopping",
		/*59*/"reading (loads of magazines)",
		/*60*/"using the computer",
		/*61*/"watching films",
		/*62*/"I prefer to spend the summer",
		/*63*/"abroad/in Spain",
		/*64*/"on the coast/in the country",
		/*65*/"in the mountains/in the city",
		/*66*/"a week/month/year ago",
		/*67*/"two weeks/months/years ago",
		/*68*/"I went on holiday to",
		/*69*/"France/Italy/Turkey",
		/*70*/"who did you go with?",
		/*71*/"I went with my family/school",
		/*72*/"I went with my best friend",
		/*73*/"I went alone",
		/*74*/"how did you travel?",
		/*75*/"I travelled",
		/*76*/"by coach/plane",
		/*77*/"by coach/car/train",
		/*78*/"first",
		/*79*/"then",
		/*80*/"later",
		/*81*/"after",
		/*82*/"finally",
		/*83*/"the best thing was when",
		/*84*/"the worst thing was when",
		/*85*/"I learned to sail",
		/*86*/"I ate lots of ice creams",
		/*87*/"I bought souvenirs",
		/*88*/"I rested",
		/*89*/"I went to the aquarium",
		/*90*/"I went sightseeing",
		/*91*/"I arrived at the airport late",
		/*92*/"I lost my mobile",
		/*93*/"I took photos",
		/*94*/"I sunbathed",
		/*95*/"I had an accident on the beach",
		/*96*/"I watched a match",
		/*97*/"I visited the park",
		/*98*/"I was sick on a roller coaster",
		/*99*/"you can discover the Picasso Museum",
		/*100*/"you can enjoy the gothic quarter",
		/*101*/"you can walk along the Ramblas",
		/*102*/"you can go up the Columbus Monument",
		/*103*/"you can watch the boats in the port",
		/*104*/"I like/I love",
		/*105*/"I had a great/phenomenal time",
		/*106*/"I had a good/bad/awful time",
		/*107*/"it was unforgettable/incredible",
		/*108*/"it was impressive/awesome",
		/*109*/"it was awful",
		/*110*/"it was a disaster",
		/*111*/"what was the weather like?",
		/*112*/"it was good/bad weather",
		/*113*/"it was hot/cold/sunny/windy",
		/*114*/"it was foggy/stormy",
		/*115*/"it rained/snowed",
		/*116*/"I stayed",
		/*117*/"I stayed",
		/*118*/"We stayed",
		/*119*/"We stayed",
		/*120*/"in a youth hostel",
		/*121*/"in an apartment",
		/*122*/"in a campsite",
		/*123*/"in a five star hotel",
		/*124*/"in a state run luxury hotel",
		/*125*/"in a house in the country",
		/*126*/"in a guest house",
		/*127*/"I went on a cruise",
		/*128*/"it was near the beach",
		/*129*/"it was in the city centre",
		/*130*/"it was on the outskits",
		/*131*/"it was",
		/*132*/"it was welcoming",
		/*133*/"it was old",
		/*134*/"it was cheap",
		/*135*/"it was expensive",
		/*136*/"it was big",
		/*137*/"it was luxurious",
		/*138*/"it was modern",
		/*139*/"it was small",
		/*140*/"it was noisy",
		/*141*/"it was quiet",
		/*142*/"it had/there was",
		/*143*/"it has neither... nor...",
		/*144*/"there was neither... nor...",
		/*145*/"nor did it have",
		/*146*/"cap park",
		/*147*/"bar",
		/*148*/"gym",
		/*149*/"restaurant",
		/*150*/"cafe",
		/*151*/"launderette",
		/*152*/"(indoor) pool",
		/*153*/"lots of space for my tent",
		/*154*/"the good thing about the town/village/city",
		/*155*/"the bad thing was that it was",
		/*156*/"too/very/quite",
		/*157*/"lively",
		/*158*/"pretty",
		/*159*/"historic",
		/*160*/"picturesque",
		/*161*/"touristic",
		/*162*/"it had lots of atmosphere/traffic",
		/*163*/"it had lots to do",
		/*164*/"it had lots of pollution/people",
		/*165*/"it had lots of green spaces",
		/*166*/"it had lots of places of interest",
		/*167*/"it had lots of discos",
		/*168*/"is there free wifi?",
		/*169*/"is there air conditioning",
		/*170*/"in the hotel/the rooms",
		/*171*/"how much does a (big) room cost?",
		/*172*/"what time is breakfast served",
		/*173*/"what time does the pool open?",
		/*174*/"how much is the supplement for?",
		/*175*/"are dogs allowed?",
		/*176*/"i would like to book",
		/*177*/"a single/double room",
		/*178*/"with/without a balcony",
		/*179*/"with a bath/shower",
		/*180*/"with a double bed",
		/*181*/"with breakfast included",
		/*182*/"with half board",
		/*183*/"with full board",
		/*184*/"with a sea view",
		/*185*/"for how many nights?",
		/*186*/"for forteen nights",
		/*187*/"from the seventeenth to the thirty first of August",
		/*188*/"can you repeat, please?",
		/*189*/"can you speak slower?",
		/*190*/"I want to speak to the manager",
		/*191*/"I want to change rooms",
		/*192*/"the air conditioning",
		/*193*/"the elevator",
		/*194*/"the shower",
		/*195*/"the room is dirty",
		/*196*/"the light does not work",
		/*197*/"there are rats in the bed",
		/*198*/"there is no",
		/*199*/"I need",
		/*200*/"toilet paper",
		/*201*/"soap/shampoo",
		/*202*/"towels/hairdryer",
		/*203*/"help!",
		/*204*/"it is unacceptable",
		/*205*/"sorry",
		/*206*/"the hotel is full",
		/*207*/"unfortunately",
		/*208*/"on the one hand... on the other hand...",
		/*209*/"on the first/last day",
		/*210*/"on the following day",
		/*211*/"I had/we had",
		/*212*/"an accident/a puncture",
		/*213*/"a delay/a breakdown",
		/*214*/"I had to/we had to",
		/*215*/"wait a long time",
		/*216*/"go to the hospital/to the police station",
		/*217*/"call a mechanic",
		/*218*/"I lost/we lost",
		/*219*/"the luggage/the wallet",
		/*220*/"the suitcase/the keys",
		/*221*/"when we arrived",
		/*222*/"it was very late",
		/*223*/"I was tired",
		/*224*/"the reception was already closed",
		/*225*/"to camp",
		/*226*/"to decide",
		/*227*/"to hire bikes",
		/*228*/"to take the cable car",
		/*229*/"to crash into",
		/*230*/"to go mountain climbing",
		/*231*/"to return",
		/*232*/"the landscape",
		/*233*/"the motorway",
		/*234*/"beautiful",
		/*235*/"drama",
		/*236*/"art",
		/*237*/"Spanish",
		/*238*/"English",
		/*239*/"biology",
		/*240*/"PE",
		/*241*/"physics",
		/*242*/"geography",
		/*243*/"history",
		/*244*/"ICT",
		/*245*/"language",
		/*246*/"chemistry",
		/*247*/"RE",
		/*248*/"technology",
		/*249*/"languages",
		/*250*/"business studies",
		/*251*/"maths",
		/*252*/"science",
		/*253*/"subject",
		/*254*/"I’m interested in / fascinated by",
		/*255*/"what is your school like?",
		/*256*/"my favourite day is Friday",
		/*257*/"my timetable",
		/*258*/"what day do you have physics",
		/*259*/"I have English on Tuesdays.",
		/*260*/"what time do you have business studies",
		/*261*/"at one o’clock / at two o’clock",
		/*262*/"quarter past / to",
		/*263*/"five past / to",
		/*264*/"half past",
		/*265*/"pre school / primary education",
		/*266*/"secondary education",
		/*267*/"A levels",
		/*268*/"vocational training",
		/*269*/"Geography is more / less interesting than ICT",
		/*270*/"is better / worse than...",
		/*271*/"as... as...",
		/*272*/"easy / difficult",
		/*273*/"fun / boring",
		/*274*/"useful / relevant / practical",
		/*275*/"creative / relaxing",
		/*276*/"precise / logical / demanding",
		/*277*/"my science teacher is...",
		/*278*/"patient / impatient",
		/*279*/"tolerant / harsh",
		/*280*/"clever / stupid",
		/*281*/"hard working / lazy",
		/*282*/"nice / strict",
		/*283*/"how are your studies?",
		/*284*/"teaches / explains well",
		/*285*/"has a good sense of humour",
		/*286*/"has high expectations",
		/*287*/"creates a good working atmosphere",
		/*288*/"never gets angry",
		/*289*/"makes me think",
		/*290*/"gives us advice / strategies",
		/*291*/"gives us lots of homework",
		/*292*/"academic year",
		/*293*/"tests / assessments",
		/*294*/"to fail / to pass",
		/*295*/"in my school there is...",
		/*296*/"my school has...",
		/*297*/"a hall / drama studio",
		/*298*/"a canteen",
		/*299*/"a football pitch",
		/*300*/"a playground",
		/*301*/"Are you interested in chemistry?",
		/*302*/"what is your school day like?",
		/*303*/"a library",
		/*304*/"a tennis court / an athletics track",
		/*305*/"some laboratories",
		/*306*/"lots of classrooms",
		/*307*/"the good / bad thing is that...",
		/*308*/"the best / worst thing is that...",
		/*309*/"What I like most is / are...",
		/*310*/"What I like least is / are...",
		/*311*/"not a single...",
		/*312*/"no one",
		/*313*/"mixed / all girls / all boys",
		/*314*/"state / private",
		/*315*/"modern / old",
		/*316*/"in my primary school there was/were...",
		/*317*/"my primary school had...",
		/*318*/"exams / homework / pupils",
		/*319*/"furniture / green spaces",
		/*320*/"free time",
		/*321*/"opportunities / facilities",
		/*322*/"interactive whiteboards / lessons",
		/*323*/"ICT rooms",
		/*324*/"somewhere to play",
		/*325*/"little space",
		/*326*/"before / now",
		/*327*/"the building / the school",
		/*328*/"the school day",
		/*329*/"(in)adequate / short",
		/*330*/"long",
		/*331*/"the lessons are / were...",
		/*332*/"I have to wear...",
		/*333*/"we have to wear...",
		/*334*/"I (don’t) wear...",
		/*335*/"we (don’t) wear...",
		/*336*/"it is compulsory to wear...",
		/*337*/"a (knitted) sweater",
		/*338*/"a dress",
		/*339*/"a shirt",
		/*340*/"a t-shirt",
		/*341*/"a (striped) jacket",
		/*342*/"a cardigan",
		/*343*/"a tie",
		/*344*/"a (checked) skirt",
		/*345*/"trousers",
		/*346*/"socks",
		/*347*/"shoes",
		/*348*/"jeans",
		/*349*/"tights",
		/*350*/"yellow",
		/*351*/"white",
		/*352*/"black",
		/*353*/"red",
		/*354*/"purple",
		/*355*/"orange",
		/*356*/"pink",
		/*357*/"blue",
		/*358*/"green",
		/*359*/"grey",
		/*360*/"brown",
		/*361*/"dark / light",
		/*362*/"striped / checked",
		/*363*/"comfortable / uncomfortable",
		/*364*/"old fashioned / smart / formal",
		/*365*/"uniform",
		/*366*/"improves discipline",
		/*367*/"limits individuality",
		/*368*/"gives a positive image of the school",
		/*369*/"saves time in the morning",
		/*370*/"It is forbidden...",
		/*371*/"You are not allowed...",
		/*372*/"You must not...",
		/*373*/"chew gum",
		/*374*/"use your phone in lessons",
		/*375*/"damage the facilities",
		/*376*/"be agressive or rude",
		/*377*/"run in the corridors",
		/*378*/"have piercings",
		/*379*/"It is necessary...",
		/*380*/"be on time",
		/*381*/"wait for your turn to speak",
		/*382*/"keep the playground clean",
		/*383*/"the most important rule is...",
		/*384*/"respect others",
		/*385*/"the rules are...",
		/*386*/"necessary / too strict",
		/*387*/"for promoting good discipline",
		/*388*/"for limiting freedom of expression",
		/*389*/"for annoying the pupils",
		/*390*/"to get good / bad grades",
		/*391*/"I agree",
		/*392*/"No way!",
		/*393*/"How awful!",
		/*394*/"How great!",
		/*395*/"one problem in my school is...",
		/*396*/"exam stress",
		/*397*/"bullying",
		/*398*/"peer pressure",
		/*399*/"there are (some) pupils who...",
		/*400*/"make fun of others",
		/*401*/"are victims of intimidation",
		/*402*/"are afraid of...",
		/*403*/"bunk",
		/*404*/"want to be part of the friendship group",
		/*405*/"are a bad influence",
		/*406*/"I leave home at...",
		/*407*/"school rules",
		/*408*/"on foot / walking",
		/*409*/"by bike / by bus / by car",
		/*410*/"by underground / by taxi / by train",
		/*411*/"lessons start / finish at...",
		/*412*/"we have seven lessons per day",
		/*413*/"each lessons lasts forty five minutes.",
		/*414*/"break / lunch is at...",
		/*415*/"arrive / go out / be",
		/*416*/"purple",
		/*417*/"wear casual clothes",
		/*418*/"go / eat together",
		/*419*/"do a guided tour",
		/*420*/"see the buildings",
		/*421*/"spend the whole day in...",
		/*422*/"attend lessons",
		/*423*/"practice Spanish",
		/*424*/"go on a trip",
		/*425*/"have a varied programme",
		/*426*/"it is going to...",
		/*427*/"be easy / cool",
		/*428*/"extra curricular activities",
		/*429*/"I play the trumpet...",
		/*430*/"I sing in the choir...",
		/*431*/"I go to the chess club",
		/*432*/"I am a member of the reporting club",
		/*433*/"chess / judo / drama / reporters",
		/*434*/"reading / eco schools / photography",
		/*435*/"I think that...",
		/*436*/"a lot of fun",
		/*437*/"something different / an achievement",
		/*438*/"they help you to...",
		/*439*/"forget the pressures of school",
		/*440*/"develop your talents",
		/*441*/"make new friends",
		/*442*/"they give you...",
		/*443*/"a sense of achievement",
		/*444*/"more confidence",
		/*445*/"the opportunity to be creative",
		/*446*/"the opportunity to express yourself",
		/*447*/"last year / term / summer...",
		/*448*/"I took part in a special event",
		/*449*/"a concert / a competition / a tournament",
		/*450*/"a subject",
		/*451*/"I won a trophy",
		/*452*/"I played a solo",
		/*453*/"we achieved the award",
		/*454*/"as...",
		/*455*/"we had a talk / presentation",
		/*456*/"we won a national competition",
		/*457*/"we gave a concert",
		/*458*/"It was a success!",
		/*459*/"this term / next term",
		/*460*/"I am going to...",
		/*461*/"learn to...",
		/*462*/"continue with...",
		/*463*/"Stop!",
		/*464*/"sign up for the drama club",
		/*465*/"we are going to...",
		/*466*/"put on a play",
		/*467*/"achieve...",
	],
];

var correct = 0;
var incorrect = 0;
var random = 0;
var random2 = 0;
var done = false;
var cheat = false;

function ask(){
	done = false;
	cheat = false;
	document.getElementById("idontknow").innerHTML = "I don't know";
	document.getElementById("dontknow").innerHTML = "";
	document.getElementById("answer").value = "";
	random = Math.floor(Math.random()*questions.length);
	random2 = Math.floor(Math.random()*questions[random].length);
	document.getElementById("question").innerHTML = questions[random][random2];
}
ask();

function check(){
	if(answers[random][random2].replace(/ /g,"").toLowerCase() == document.getElementById("answer").value.replace(/ /g,"").toLowerCase()){
		if(!done){
			correct++;
			document.getElementById("correct").innerHTML = "correct: " + correct;
		}
	ask();
	}else if(!done){
		done = true;
		incorrect++;
		document.getElementById("incorrect").innerHTML = "incorrect: " + incorrect;
	}
}

document.getElementById("enter").onclick = function(){
	check();
};

document.getElementById("idontknow").onclick = function(){
	if(document.getElementById("idontknow").innerHTML == ("I don't know") && done && !cheat){
		document.getElementById("dontknow").innerHTML = answers[random][random2];
		document.getElementById("idontknow").innerHTML = "I was right";
	}else if(!done){
		cheat = true;
		done = true;
		incorrect++;
		document.getElementById("incorrect").innerHTML = "incorrect: " + incorrect;
		document.getElementById("dontknow").innerHTML = answers[random][random2];
	}else if(!cheat){
		incorrect--;
		document.getElementById("incorrect").innerHTML = "incorrect: " + incorrect;
		correct++;
		document.getElementById("correct").innerHTML = "correct: " + correct;
		ask();
	}
};

window.addEventListener('keyup', function(ev){
	if(ev.keyCode == 13){
		check();
	}
});