var questions = [
	[ /*physics*//*0*/
		/*0*/"&#9651E =",
		/*1*/"&#9651T =",
		/*2*/"Specific heat capactity is the...",
		/*3*/"&#961; =",
		/*4*/"Mass in a change of state...",
		/*5*/"Specific heat capacity is different for...",
		/*6*/"Ineternal energy is the...",
		/*7*/"Heating either...",
		/*8*/"The energy needed for a change of state is called...",
		/*9*/"Latent heat is the...",
		/*10*/"When a change of state occurs, the temperature...",
		/*11*/"When a change of state occurs, the heat...",
		/*12*/"Specific latent heat is the...",
		/*13*/"E (energy for a change of state) =",
		/*14*/"Latent heat of fusion is the...",
		/*15*/"Latent heat of vaporisation is the...",
		/*16*/"The energy required to change a solid to a liquid is called...",
		/*17*/"The energy required to change a liquid to a solid is called...",
		/*18*/"The energy required to change a liquid to a gas is called...",
		/*19*/"The energy required to change a gas to a liquid is called...",
		/*20*/"The particle model explains...",
		/*21*/"Molecules in gas are in...",
		/*22*/"The temperature is related to the...",
		/*23*/"In a gas at constant volume, the temperature(K) is...",
		/*24*/"In a gas at constant volume, the pressure is...",
		/*25*/"In a gas at constant pressure, the temperature(K) is...",
		/*26*/"In a gas at constant pressure, the volume is...",
		/*27*/"In a gas at constant temperature, the volume is...",
		/*28*/"In a gas at constant temperature, the pressure is...",
		/*29*/"P x V =",
		/*30*/"T/V =",
		/*31*/"T/P =",
		/*32*/"P<sub>1</sub>V<sub>1</sub> =",
		/*33*/"T<sub>1</sub>/V<sub>1</sub> =",
		/*34*/"T<sub>1</sub>/P<sub>1</sub> =",
		/*35*/"Pressure produces a...",
		/*36*/"Doing work on a gas can...",
		/*37*/"When work is done a gas....so the temperature of the gas increases",
	],
	[ /*computing*//*1*/
		/*0*/"CPU stands for...",
		/*1*/"ALU stands for...",
		/*2*/"ACC stands for...",
		/*3*/"CU stands for...",
		/*4*/"MAR stands for...",
		/*5*/"MDR stands for...",
		/*6*/"PC stands for...",
		/*7*/"CIR stands for...",
		/*8*/"The seven components in the Von Neumann architecture are...",
		/*9*/"The three buses in the Von Neumann architecture are...",
		/*10*/"The adress bus is used by the...",
		/*11*/"The data bus is used by the...",
		/*12*/"The control bus is used by the...",
		/*13*/"The ALU...",
		/*14*/"The ACC...",
		/*15*/"The CU...",
		/*16*/"The MAR...",
		/*17*/"The MDR...",
		/*18*/"The PC...",
		/*19*/"The CIR...",
		/*20*/"An embedded system provides...",
		/*21*/"An embedded system consists of a...",
		/*22*/"Advantages of an embedded system include...",
		/*23*/"Embedded system example: W...",
		/*24*/"Embedded system example: S...",
		/*25*/"Embedded system example: A...",
		/*26*/"Embedded system example: B...",
		/*27*/"Embedded system example: I...",
		/*28*/"Embedded system example: H...",
	],
	[ /*geogrpahy*//*2*/
		/*0*/"Weather cells in order from the equator:",
		/*1*/"Hadley cell position:",
		/*2*/"Ferrel cell position:",
		/*3*/"Polar cell position:",
		/*4*/"The weakest weather cell is the...",
		/*5*/"The strongest weather cell is the...",
		/*6*/"Trade winds blow from the...",
		/*7*/"Air at the equator is...",
		/*8*/"Air in the tropics is...",
		/*9*/"When air rises, pressure is...",
		/*10*/"When air sinks, pressure is...",
		/*11*/"When pressure is high, air is...",
		/*12*/"When pressure is low, air is...",
		/*13*/"Precipitation occurs at...",
		/*14*/"Sun occurs at...",
		/*15*/"Trade winds blow towards the...",
		/*16*/"The most complicated weather cell is the...",
		/*17*/"At hight pressure, the temperature is...",
		/*18*/"At low pressure, the temperature is...",
		/*19*/"The temperature is more varied at...",
		/*20*/"The temperature is less varied at...",
	],
	[ /*chemistry*//*3*/
		/*0*/"Three limitations of the particle model are...",
		/*1*/"Can physical changes be reversed?",
		/*2*/"Can chemical changes be reversed?",
		/*3*/"Freezing juice is a...",
		/*4*/"Mixing sand and water is a...",
		/*5*/"Dissolving sugar in water is a...",
		/*6*/"Cooking eggs is a...",
		/*7*/"Cooking cakes is a...",
		/*8*/"Steel rusting is a...",
		/*9*/"Acid + Alkali is a...",
		/*10*/"In a physical change...",
		/*11*/"In a chemical change...",
		/*12*/"A meolceule is...",
		/*13*/"Isotopes have...",
		/*14*/"Hydrogen-2 has...",
		/*15*/"Ions have...",
		/*16*/"Atomic radius is the...",
		/*17*/"Bond length is the...",
		/*18*/"In metres, atomic radius is around...",
		/*19*/"In the most suitable unit, atomic radius is around...",
		/*20*/"<super>z</super>X is the...",
		/*21*/"<sub>z</sub>X is the...",
		/*22*/"The mass number is the number of...",
		/*23*/"The atomic number is the number of...",
		/*24*/"Most of an atom is...",
		/*25*/"Compared to the atom's size, the nucleus is...",
		/*26*/"Compared to a proton, electrons are...",
		/*27*/"John Dalton made the...",
		/*28*/"Joseph John Thomson made the...",
		/*29*/"Ernest Rutherford made the...",
		/*30*/"Niels Bohr made the...",
		/*31*/"The plum pudding model was made because...",
		/*32*/"The planetary model was made because...",
		/*33*/"The nuclear model was made because...",
	],
	[ /*spanish*//*4*/
		/*0*/"Vivo en el",
		/*1*/"norte/noreste/noroeste",
		/*2*/"sur/sureste/suroeste",
		/*3*/"este/oeste/centro",
		/*4*/"Inglaterra/Escocia",
		/*5*/"Gales/Irlanda (del norte)",
		/*6*/"En verano/invierno",
		/*7*/"chateo en la red",
		/*8*/"cocino para mi familia",
		/*9*/"descargo canciones",
		/*10*/"escribo correos",
		/*11*/"hago nataci&#243;n/esqu&#237;/windsurf",
		/*12*/"hago una barbacoa",
		/*13*/"juego al baloncesto/f&#250;tbol",
		/*14*/"monto a caballo/en bici",
		/*15*/"nado en el mar",
		/*16*/"salgo con mis amigos/as",
		/*17*/"toco la guitarra",
		/*18*/"trabajo como voluntario/a",
		/*19*/"veo la tele",
		/*20*/"voy al polideportivo/al parque/a un centro comercial",
		/*21*/"voy de paseo",
		/*22*/"siempre",
		/*23*/"a menudo",
		/*24*/"todos los d&#237;as",
		/*25*/"a veces",
		/*26*/"de vez en cuando",
		/*27*/"una vez a la semana",
		/*28*/"dos o tres veces al a&#241;o",
		/*29*/"(casi) nunca",
		/*30*/"Hace buen/mal tiempo",
		/*31*/"Hace calor/fr&#237;o/sol/viento",
		/*32*/"Llueve/Nieva",
		/*33*/"El tiempo es variable",
		/*34*/"El clima es caluroso/soleado",
		/*35*/"Hay niebla/tormenta",
		/*36*/"Hay chubascos",
		/*37*/"Est&#225; nublado",
		/*38*/"Soy adicto/a a...",
		/*39*/"Soy un(a) fan&#225;tico/a de...",
		/*40*/"ya que/dado que/puesto que",
		/*41*/"Prefiero...",
		/*42*/"Me gusta...",
		/*43*/"Me encanta",
		/*44*/"Me mola",
		/*45*/"Me chifla",
		/*46*/"Me flipa",
		/*47*/"Me apasiona...",
		/*48*/"No me gusta (nada)...",
		/*49*/"Odio...",
		/*50*/"A mi padre le gusta...",
		/*51*/"Nos encanta",
		/*52*/"bucear",
		/*53*/"estar al aire libre",
		/*54*/"estar en contacto con los amigos",
		/*55*/"hacer artes marciales",
		/*56*/"hacer deportes acu&#225;ticos",
		/*57*/"ir al cine/a la pista de hielo",
		/*58*/"ir de compras",
		/*59*/"leer (un mont&#243;n de revistas)",
		/*60*/"usar el ordenador",
		/*61*/"ver pel&#237;culas",
		/*62*/"Prefiero veranear...",
		/*63*/"en el extranjero/en Espa&#241;a",
		/*64*/"en la costa/en el campo",
		/*65*/"en la monta&#241;a/en la ciudad",
		/*66*/"hace una semana/un mes/un a&#241;o",
		/*67*/"hace dos semanas/meses/a&#241;os",
		/*68*/"fui de vacaciones a...",
		/*69*/"Francia/Italia/Turqu&#237;a",
		/*70*/"&#191;Con qui&#233;n fuiste?",
		/*71*/"Fui con mi familia/insti",
		/*72*/"Fui con mi mejor amigo/a",
		/*73*/"Fui solo/a",
		/*74*/"&#191;C&#243;mo viajaste?",
		/*75*/"Viaj&#233;...",
		/*76*/"en autocar/avi&#243;n",
		/*77*/"en barco/coche/tren",
		/*78*/"primero",
		/*79*/"luego",
		/*80*/"m&#225;s tarde",
		/*81*/"despu&#233;s",
		/*82*/"finalmente",
		/*83*/"Lo mejor fue cuando...",
		/*84*/"Lo peor fue cuando...",
		/*85*/"aprend&#237; a hacer vela",
		/*86*/"com&#237; muchos helados",
		/*87*/"compr&#233; recuerdos",
		/*88*/"descans&#233;",
		/*89*/"fui al acuario",
		/*90*/"hice turismo",
		/*91*/"llegu&#233; tarde al aeropuerto",
		/*92*/"perd&#237; mi m&#243;vil",
		/*93*/"saqu&#233; fotos",
		/*94*/"tom&#233; el sol",
		/*95*/"tuve un accidente en la playa",
		/*96*/"vi un partido",
		/*97*/"visit&#233; el park",
		/*98*/"vomit&#233; en una monta&#241;a rusa",
		/*99*/"Puedes descubrir el Museo Picasso",
		/*100*/"Puedes disfrutar del Barrio G&#243;tico",
		/*101*/"Puedes pasear por las Ramblas",
		/*102*/"Puedes subir al Monumento a Col&#243;n",
		/*103*/"Puedes ver los barcos en el puerto",
		/*104*/"Me gust&#243;/Me encant&#243;",
		/*105*/"Lo pas&#233; bomba/fenomenal",
		/*106*/"Lo pas&#233; bien/mal/fatal",
		/*107*/"Fue inolvidable/incre&#237;ble",
		/*108*/"Fue impresionante/flipante",
		/*109*/"Fue horroroso",
		/*110*/"Fue un desastre",
		/*111*/"&#191;Qu&#233; tiempo hizo?",
		/*112*/"Hizo buen/mal tiempo",
		/*113*/"Hizo calor/fr&#237;o/sol/viento",
		/*114*/"Hubo niebla/tormenta",
		/*115*/"Llovi&#243;/Nev&#243;",
		/*116*/"Me aloj&#233;",
		/*117*/"Me qued&#233;",
		/*118*/"Nos alojamos",
		/*119*/"Nos quedamos",
		/*120*/"en un albergue juvenil",
		/*121*/"en un apartamento",
		/*122*/"en un camping",
		/*123*/"en un hotel de cinco estrellas",
		/*124*/"en un parador",
		/*125*/"en una casa rural",
		/*126*/"en una pensi&#243;n",
		/*127*/"Fui de crucero",
		/*128*/"Estaba cerca de la playa",
		/*129*/"Estaba en el centro de la ciudad",
		/*130*/"Estaba en las afueras",
		/*131*/"Era...",
		/*132*/"Era acogedor(a)",
		/*133*/"Era antiguo/a",
		/*134*/"Era barato/a",
		/*135*/"Era caro/a",
		/*136*/"Era grande",
		/*137*/"Era lujoso",
		/*138*/"Era moderno/a",
		/*139*/"Era peque&#241;o/a",
		/*140*/"Era ruidoso/a",
		/*141*/"Era tranquilo/a",
		/*142*/"Ten&#237;a/Hab&#237;a...",
		/*143*/"No ten&#237;a ni... ni...",
		/*144*/"No hab&#237;a ni... ni...",
		/*145*/"Tampoco ten&#237;a...",
		/*146*/"aparcamiento",
		/*147*/"bar",
		/*148*/"gimnasio",
		/*149*/"restaurante",
		/*150*/"cafeter&#237;a",
		/*151*/"lavander&#237;a",
		/*152*/"piscina (cubierta)",
		/*153*/"mucho espacio para mi tienda",
		/*154*/"Lo bueno del pueblo/de la ciudad",
		/*155*/"Lo malo era que era...",
		/*156*/"demasiado/muy/bastante...",
		/*157*/"animado/a",
		/*158*/"bonito/a",
		/*159*/"hist&#243;rico/a",
		/*160*/"pintoresco/a",
		/*161*/"tur&#237;stico/a",
		/*162*/"Ten&#237;a mucho ambiente/tr&#225;fico",
		/*163*/"Ten&#237;a mucho que hacer",
		/*164*/"Ten&#237;a mucha contaminaci&#243;n/gente",
		/*165*/"Ten&#237;a muchos espacios verdes",
		/*166*/"Ten&#237;a muchos lugares de inter&#233;s",
		/*167*/"Ten&#237;a muchas discotecas",
		/*168*/"&#191;Hay wifi gratis?",
		/*169*/"&#191;Hay aire acondicionado?",
		/*170*/"en el hotel/las habitaciones",
		/*171*/"&#191;Cu&#225;nto cuesta una habitaci&#243;n (grande)?",
		/*172*/"&#191;A qu&#233; hora se sirve el desayuno?",
		/*173*/"&#191;Cu&#225;ndo est&#225; abierta la piscina?",
		/*174*/"&#191;Cu&#225;nto es el suplemento por...?",
		/*175*/"&#191;Se admiten perros?",
		/*176*/"Quisiera reservar...",
		/*177*/"una habitaci&#243;n individual/doble",
		/*178*/"con/sin balc&#243;n",
		/*179*/"con ba&#241;era/ducha",
		/*180*/"con cama de matrimonio",
		/*181*/"con desayuno incluido",
		/*182*/"con media pensi&#243;n",
		/*183*/"con pensi&#243;n completa",
		/*184*/"con vistas al mar",
		/*185*/"&#191;Para cu&#225;ntas noches?",
		/*186*/"Para catorce noches",
		/*187*/"del diecisiete al treinta y uno de agosto",
		/*188*/"&#191;Puede repetir, por favor?",
		/*189*/"&#191;Puede hablar m&#225;s despacio?",
		/*190*/"Quiero hablar con el director",
		/*191*/"Quiero cambiar de habitaci&#243;n",
		/*192*/"El aire acondicionado",
		/*193*/"El ascensor",
		/*194*/"La ducha",
		/*195*/"La habitaci&#243;n est&#225; sucio/a",
		/*196*/"La luz no funciona",
		/*197*/"Hay ratas en la cama",
		/*198*/"No hay...",
		/*199*/"Necesito...",
		/*200*/"papel higi&#233;nico",
		/*201*/"jab&#243;n/champ&#250;",
		/*202*/"toallas/secador",
		/*203*/"¡Socorro!",
		/*204*/"Es inaceptable",
		/*205*/"Lo siento/Perdone",
		/*206*/"El hotel est&#225; completo",
		/*207*/"Por desgracia",
		/*208*/"Por un lado... por otro lado...",
		/*209*/"El primer/&#250;ltimo d&#237;a",
		/*210*/"Al d&#237;a siguiente",
		/*211*/"Tuve/Tuvimos...",
		/*212*/"un accidente/un pinchazo",
		/*213*/"un retraso/una aver&#237;a",
		/*214*/"Tuve/Tuvimos que...",
		/*215*/"esperar mucho tiempo",
		/*216*/"ir al hospital/a la comisar&#237;a",
		/*217*/"llamar a un mec&#225;nico",
		/*218*/"Perd&#237;/Perdimos...",
		/*219*/"el equipaje/la cartera",
		/*220*/"la maleta/las llaves",
		/*221*/"Cuando llegamos...",
		/*222*/"era muy tarde",
		/*223*/"estaba cansado/a",
		/*224*/"la recepci&#243;n ya estaba cerrada",
		/*225*/"acampar",
		/*226*/"decidir",
		/*227*/"alquilar bicicletas",
		/*228*/"coger el telef&#233;rico",
		/*229*/"chocar con",
		/*230*/"hacer alpinismo",
		/*231*/"volver",
		/*232*/"el paisaje",
		/*233*/"la autopista",
		/*234*/"precioso/a",
	],
];
var answers = [
	[ /*physics*//*0*/
		/*0*/"mcDT",
		/*1*/"DE/mc",
		/*2*/"energy required to raise 1kg by 1oC",
		/*3*/"m/V",
		/*4*/"is conserved",
		/*5*/"different materials",
		/*6*/"total kinetic and potential energy of all the particles",
		/*7*/"raises the temperature or changes the state",
		/*8*/"latent heat",
		/*9*/"energy needed for a change of state",
		/*10*/"stays the same",
		/*11*/"changes",
		/*12*/"energy needed to change the state of 1kg",
		/*13*/"mL",
		/*14*/"energy needed to change the state between solid and liquid",
		/*15*/"energy needed to change the state between liquid and gas",
		/*16*/"latent heat of fusion",
		/*17*/"latent heat of fusion",
		/*18*/"latent heat of vaporisation",
		/*19*/"latent heat of vaporisation",
		/*20*/"states of matter and differences in density",
		/*21*/"constant random motion",
		/*22*/"average kinetic energy",
		/*23*/"proportional to the pressure",
		/*24*/"proportional to the temperature(K)",
		/*25*/"proportional to the volume",
		/*26*/"proportional to the temperature(K)",
		/*27*/"inversely proportional to the pressure",
		/*28*/"inversely proportional to the volume",
		/*29*/"k",
		/*30*/"k",
		/*31*/"k",
		/*32*/"P2V2",
		/*33*/"T2/V2",
		/*34*/"T2/P2",
		/*35*/"net force at right angles to the walls of the container",
		/*36*/"increase it's temperature",
		/*37*/"kinetic energy is transferred to the particles so the average kinetic energy increases",
	],
	[ /*computing*//*1*/
		/*0*/"Central Processing Unit",
		/*1*/"Arithmetic and Logic Unit",
		/*2*/"Accumulator",
		/*3*/"Control Unit",
		/*4*/"Memory Address Register",
		/*5*/"Memory Data Register",
		/*6*/"Program Counter",
		/*7*/"Current Instruction Register",
		/*8*/"ALU, ACC, CU, MAR, MDR, PC, CIR",
		/*9*/"Address bus, Data bus, Control bus",
		/*10*/"MAR",
		/*11*/"MDR",
		/*12*/"CU",
		/*13*/"does all the maths",
		/*14*/"stores the data being used in ALU",
		/*15*/"controls what the other components in the CPU are doing",
		/*16*/"stores the address in the memory to be fetched or sent to",
		/*17*/"stores data that has been fetched from or to be sent to the memory",
		/*18*/"holds the address in the memory of the next instruction (IP) (IAR)",
		/*19*/"holds the address in the memory of the current instruction",
		/*20*/"one or two specific functions",
		/*21*/"microprocessor that takes in an input, processes it, and povides an output",
		/*22*/"Smaller and cheaper because their is less wastage",
		/*23*/"Washing machine",
		/*24*/"Smoke detector",
		/*25*/"Air conditioning",
		/*26*/"Blood pressure monitor",
		/*27*/"Insulin pump",
		/*28*/"Headlight position control",
	],
	[ /*geogrpahy*//*2*/
		/*0*/"Hadley, Ferrel, Polar",
		/*1*/"0-30/40",
		/*2*/"30/40-60/70",
		/*3*/"60/70-90",
		/*4*/"Polar cell",
		/*5*/"Hadley cell",
		/*6*/"East",
		/*7*/"rising",
		/*8*/"sinking",
		/*9*/"low",
		/*10*/"high",
		/*11*/"sinking",
		/*12*/"rising",
		/*13*/"low pressure",
		/*14*/"high pressure",
		/*15*/"equator",
		/*16*/"Ferrel cell",
		/*17*/"varied",
		/*18*/"constant",
		/*19*/"high pressure",
		/*20*/"low pressure",
	],
	[ /*chemistry*//*3*/
		/*0*/"forces between particles, size of particles, space between particles",
		/*1*/"yes",
		/*2*/"no",
		/*3*/"physical change",
		/*4*/"physical change",
		/*5*/"physical change",
		/*6*/"chemical change",
		/*7*/"chemical change",
		/*8*/"chemical change",
		/*9*/"chemical change",
		/*10*/"no new substances are produced",
		/*11*/"new substances are produced",
		/*12*/"two or more atoms joined together",
		/*13*/"different numbers of neutrons",
		/*14*/"two neutrons",
		/*15*/"different numbers of electrons",
		/*16*/"distance between the centre and the edge of an atom",
		/*17*/"distance between the centres of two connected atoms",
		/*18*/"10-10",
		/*19*/"0.1nm",
		/*20*/"mass number",
		/*21*/"atomic number",
		/*22*/"protons and neutrons",
		/*23*/"protons",
		/*24*/"empty space",
		/*25*/"100,000 times smaller",
		/*26*/"2000 times smaller",
		/*27*/"solid state model of the atom",
		/*28*/"plum pudding model of the atom",
		/*29*/"planetary model of the atom",
		/*30*/"nuclear model of the atom",
		/*31*/"cathode rays (beams of electrons) changed direction and electric and magnetic fields",
		/*32*/"alpha particles (helium nuclei) occasionally bounced off gold leaf",
		/*33*/"electrons would spiral inwards in the planetary model",
	],
	[ /*spanish*//*4*/
		/*0*/"I live in the",
		/*1*/"north/north east/north west",
		/*2*/"south/south east/south west",
		/*3*/"east/west/centre",
		/*4*/"England/Scotland",
		/*5*/"Wales/(Northern) Ireland",
		/*6*/"in summer/winter",
		/*7*/"chat online",
		/*8*/"cook for my family",
		/*9*/"download songs",
		/*10*/"write emails",
		/*11*/"I go swimming/skiing/windsurfing",
		/*12*/"I have a barbecue",
		/*13*/"I play basketball/football",
		/*14*/"horseriding/cycling",
		/*15*/"I swim in the sea",
		/*16*/"I go out with my friends",
		/*17*/"I play guitar",
		/*18*/"I work as a volunteer",
		/*19*/"I watch TV",
		/*20*/"I go to the sports centre/the park/the shopping centre",
		/*21*/"I go for a walk",
		/*22*/"always",
		/*23*/"often",
		/*24*/"every day",
		/*25*/"sometimes",
		/*26*/"from time to time",
		/*27*/"once a week",
		/*28*/"two or three times a year",
		/*29*/"(almost) never",
		/*30*/"it is good/bad weather",
		/*31*/"it is hot/cold/sunny/windy",
		/*32*/"it is raining/snowing",
		/*33*/"the weather is variable",
		/*34*/"the weather is hot/sunny",
		/*35*/"it is foggy/stormy",
		/*36*/"there are showers",
		/*37*/"it is cloudy",
		/*38*/"I am adicted to",
		/*39*/"I am a fan of",
		/*40*/"given that/since",
		/*41*/"I prefer",
		/*42*/"I like",
		/*43*/"I love",
		/*44*/"I love",
		/*45*/"I love",
		/*46*/"I love",
		/*47*/"I love",
		/*48*/"I do not like (at all)",
		/*49*/"I hate",
		/*50*/"My dad likes",
		/*51*/"We love",
		/*52*/"diving",
		/*53*/"being outside",
		/*54*/"staying in contact with my friends",
		/*55*/"doing martial arts",
		/*56*/"doing water sports",
		/*57*/"going to the cinema/ice rink",
		/*58*/"going shopping",
		/*59*/"reading (loads of magazines)",
		/*60*/"using the computer",
		/*61*/"watching films",
		/*62*/"I prefer to spend the summer",
		/*63*/"abroad/in Spain",
		/*64*/"on the coast/in the country",
		/*65*/"in the mountains/in the city",
		/*66*/"a week/month/year ago",
		/*67*/"two weeks/months/years ago",
		/*68*/"I went on holiday to",
		/*69*/"France/Itsly/Turkey",
		/*70*/"who did you go with?",
		/*71*/"I went with my family/school",
		/*72*/"I went with my best friend",
		/*73*/"I went alone",
		/*74*/"how did you travel",
		/*75*/"I travelled",
		/*76*/"by coach/plane",
		/*77*/"by coach/car/train",
		/*78*/"first",
		/*79*/"then",
		/*80*/"later",
		/*81*/"after",
		/*82*/"finally",
		/*83*/"the best thing was when",
		/*84*/"the worst thing was when",
		/*85*/"I learned to sail",
		/*86*/"I ate lots of ice creams",
		/*87*/"I bought souvenirs",
		/*88*/"I rested",
		/*89*/"I went to the aquarium",
		/*90*/"I went sightseeing",
		/*91*/"I arrived at the airport late",
		/*92*/"I lost my mobile",
		/*93*/"I took photos",
		/*94*/"I sunbathed",
		/*95*/"I had an accident on the beach",
		/*96*/"I watched a match",
		/*97*/"I visited the park",
		/*98*/"I was sick on a roller coaster",
		/*99*/"you can discover the Picasso Museum",
		/*100*/"you can enjoy the gothic quarter",
		/*101*/"you can walk along the Ramblas",
		/*102*/"you can go up the Columbus Monument",
		/*103*/"you can watch the boats in the port",
		/*104*/"I like/I love",
		/*105*/"I had a great/phenomenal time",
		/*106*/"I had a good/bad/awful time",
		/*107*/"it was unforgettable/incredible",
		/*108*/"it was impressive/awesome",
		/*109*/"it was awful",
		/*110*/"it was a disaster",
		/*111*/"what was the weather like?",
		/*112*/"it was good/bad weather",
		/*113*/"it was hot/sunny/windy",
		/*114*/"it was foggy/stormy",
		/*115*/"it rained/snowed",
		/*116*/"I stayed",
		/*117*/"I stayed",
		/*118*/"We stayed",
		/*119*/"We stayed",
		/*120*/"in a youth hostel",
		/*121*/"in an apartment",
		/*122*/"in a campsite",
		/*123*/"in a five star hotel",
		/*124*/"in a state run luxury hotel",
		/*125*/"in a house in the country",
		/*126*/"in a guest house",
		/*127*/"I went on a cruise",
		/*128*/"it was near the beach",
		/*129*/"it was in the city centre",
		/*130*/"it was on the outskits",
		/*131*/"it was",
		/*132*/"it was welcoming",
		/*133*/"it was old",
		/*134*/"it was cheap",
		/*135*/"it was expensive",
		/*136*/"it was big",
		/*137*/"it was luxurious",
		/*138*/"it was modern",
		/*139*/"it was small",
		/*140*/"it was noisy",
		/*141*/"it was quiet",
		/*142*/"it had/there was",
		/*143*/"it has neither... nor...",
		/*144*/"there was neither... nor...",
		/*145*/"nor did it have",
		/*146*/"cap park",
		/*147*/"bar",
		/*148*/"gym",
		/*149*/"restaurant",
		/*150*/"cafe",
		/*151*/"launderette",
		/*152*/"(indoor) pool",
		/*153*/"lots of space for my tent",
		/*154*/"the good thing about the town/village/city",
		/*155*/"the bad thing was that it was",
		/*156*/"too/very/quite",
		/*157*/"lively",
		/*158*/"pretty",
		/*159*/"historic",
		/*160*/"picturesque",
		/*161*/"touristic",
		/*162*/"it had lots of atmosphere/traffic",
		/*163*/"it had lots to do",
		/*164*/"it had lots of pollution/people",
		/*165*/"it had lots of green spaces",
		/*166*/"it had lots of places of interest",
		/*167*/"it had lots of discos",
		/*168*/"is there free wifi?",
		/*169*/"is there air conditioning",
		/*170*/"in the hotel/the rooms",
		/*171*/"how much does a (big) room cost?",
		/*172*/"what time is breakfast served",
		/*173*/"what time does the pool open?",
		/*174*/"how much is the supplement for?",
		/*175*/"are dogs allowed?",
		/*176*/"i would like to book",
		/*177*/"a single/double room",
		/*178*/"with/without a balcony",
		/*179*/"with a bath/shower",
		/*180*/"with a double bed",
		/*181*/"with breakfast included",
		/*182*/"with half board",
		/*183*/"with full board",
		/*184*/"with a sea view",
		/*185*/"for how many nights?",
		/*186*/"for forteen nights",
		/*187*/"from the seventeenth to the thirty first of August",
		/*188*/"can you repeat, please?",
		/*189*/"can you speak slower?",
		/*190*/"I want to speak to the manager",
		/*191*/"I want to change rooms",
		/*192*/"the air conditioning",
		/*193*/"the elevator",
		/*194*/"the shower",
		/*195*/"the room is dirty",
		/*196*/"the light does not work",
		/*197*/"there are rats in the bed",
		/*198*/"there is no",
		/*199*/"I need",
		/*200*/"toilet paper",
		/*201*/"soap/shampoo",
		/*202*/"towels/hairdryer",
		/*203*/"help!",
		/*204*/"it is unacceptable",
		/*205*/"sorry",
		/*206*/"the hotel is full",
		/*207*/"unfortunately",
		/*208*/"on the one hand... on the other hand...",
		/*209*/"on the first/last day",
		/*210*/"on the following day",
		/*211*/"I had/we had",
		/*212*/"an accident/a puncture",
		/*213*/"a delay/a breakdown",
		/*214*/"I had to/we had to",
		/*215*/"wait a long time",
		/*216*/"go to the hospital/to the police station",
		/*217*/"call a mechanic",
		/*218*/"I lost/we lost",
		/*219*/"the luggage/the wallet",
		/*220*/"the suitcase/the keys",
		/*221*/"when we arrived",
		/*222*/"it was very late",
		/*223*/"I was tired",
		/*224*/"the reception was already closed",
		/*225*/"to camp",
		/*226*/"to decide",
		/*227*/"to hire bikes",
		/*228*/"to take the cable car",
		/*229*/"to crash into",
		/*230*/"to go mountain climbing",
		/*231*/"to return",
		/*232*/"the landscape",
		/*233*/"the motorway",
		/*234*/"beautiful",
	],
];
var correct = 0;
var incorrect = 0;
var random = 0;
var random2 = 0;

function ask(){
	document.getElementById("dontknow").innerHTML = "";
	document.getElementById("answer").value = "";
	random = Math.floor(Math.random()*questions.length);
	random2 = Math.floor(Math.random()*questions[random].length);
	document.getElementById("question").innerHTML = questions[random][random2];
}
ask();

function check(){
	if(answers[random][random2].toLowerCase() == document.getElementById("answer").value.toLowerCase()){
		correct++;
		document.getElementById("correct").innerHTML = "correct: " + correct;
		ask();
	}else{
		incorrect++;
		document.getElementById("incorrect").innerHTML = "incorrect: " + incorrect;
	}
}

document.getElementById("enter").onclick = function(){
	check();
};

document.getElementById("idontknow").onclick = function(){
	document.getElementById("dontknow").innerHTML = answers[random][random2];
};

window.addEventListener('keyup', function(ev){
	if(ev.keyCode == 13){
		check();
	}
});